import {z} from 'zod';
import type {AppState,CommandEnvelope,Order,MoneyRecord,EditableCollection,Sale} from './types';
import {base,dateOf,id,iso} from './helpers';
import {orderTotal,orderBalance,purchaseBalance,responseDeadline} from './selectors';
export class DomainError extends Error {constructor(message:string){super(message);this.name='DomainError';}}
const assert:(ok:unknown,message:string)=>asserts ok=(ok,message)=>{if(!ok)throw new DomainError(message);};
const money=z.number().int().safe();const nonnegative=money.nonnegative();
const header=z.object({id:z.string().min(1),revision:z.number().int().nonnegative(),createdAt:z.string().min(1),updatedAt:z.string().min(1)}).passthrough();
const arrays=['clients','inquiries','products','options','orders','tasks','purchaseNeeds','purchases','suppliers','money','accounts','sales','costs','fairs','interactions','conversations','publications','attachments','closings','reconciliations','audit'] as const;
export function validateState(input:unknown):AppState {
 const root=z.object({schemaVersion:z.literal(1),revision:z.number().int().nonnegative(),businessId:z.string().min(1),updatedAt:z.string().min(1),settings:z.object({businessName:z.string().min(1),currency:z.literal('PEN'),timezone:z.literal('America/Lima'),startDate:z.string(),responseHours:z.number().positive().nullable(),workStart:z.number().min(0).max(24),workEnd:z.number().min(0).max(24),workDays:z.array(z.number().int().min(0).max(6)),ruleVersion:z.number().int().nonnegative(),methods:z.array(z.string()),categories:z.array(z.string()),catalogUrl:z.string(),originalPdfUrl:z.string(),standUrl:z.string(),phone:z.string(),instagram:z.string(),profiles:z.array(z.object({name:z.enum(['Mabel','Ana']),githubLogin:z.string()})),onboardingDone:z.boolean()}).passthrough(),requests:z.array(z.string())}).passthrough().safeParse(input);
 if(!root.success)throw new DomainError('El archivo no tiene el formato de Mabell Ramos o contiene datos inválidos.');
 const s=root.data as unknown as AppState;const seen=new Set<string>();
 for(const k of arrays){assert(Array.isArray(s[k]),`Falta la sección ${k}`);for(const item of s[k]){assert(header.safeParse(item).success,`Registro inválido en ${k}`);assert(!seen.has(item.id),'Hay identificadores duplicados en los registros');seen.add(item.id);}}
 assert(new Set(s.requests).size===s.requests.length,'Hay operaciones duplicadas');
 const check=(n:unknown,nullable=false,negative=false)=>assert(nullable&&n===null||typeof n==='number'&&Number.isSafeInteger(n)&&(negative||n>=0),'Un importe es inválido; los valores se guardan en céntimos');
 for(const p of s.products){assert(typeof p.name==='string'&&p.name.trim(),'El producto necesita nombre');check(p.price,true);assert(p.baseQuantity>0&&Number.isFinite(p.baseQuantity),'Unidad del producto inválida');assert(Array.isArray(p.history)&&Array.isArray(p.approvedBy)&&p.attributes&&Array.isArray(p.variants),'La ficha del producto no está completa');}
 for(const p of s.options){check(p.price,true);assert(p.name.trim()&&Array.isArray(p.items)&&Array.isArray(p.history),'Opción comercial inválida');for(const item of p.items)assert(item.quantity>0&&s.products.some(p=>p.id===item.productId),'El paquete contiene un producto o cantidad inválidos');}
 for(const o of s.orders){check(o.total);check(o.extra);check(o.discount);check(o.transport,true);check(o.cancelCharge);check(o.costEstimate,true);assert(Array.isArray(o.lines)&&Array.isArray(o.scope)&&Array.isArray(o.versions),'Pedido inválido');assert(['Borrador','Por confirmar','Confirmado','En preparación','Entregado','Cancelado'].includes(o.status),'Estado de pedido inválido');for(const l of o.lines){check(l.unitPrice,true);assert(l.quantity>0&&Number.isFinite(l.quantity)&&l.baseQuantity>0&&Number.isFinite(l.baseQuantity),'Cantidad o unidad inválida');assert(Array.isArray(l.distribution),'Distribución inválida');for(const d of l.distribution)assert(Number.isFinite(d.quantity)&&d.quantity>=0,'Las cantidades por variante deben ser no negativas');if(l.distribution.length)assert(Math.abs(l.distribution.reduce((n,v)=>n+v.quantity,0)-l.quantity*l.unitsPerPack)<1e-6,'La distribución de sabores debe coincidir con la cantidad de unidades');}assert(o.total===orderTotal(o),'El total del pedido no coincide con sus conceptos');if(o.clientId)assert(s.clients.some(c=>c.id===o.clientId),'El cliente del pedido no existe');if(o.status==='Entregado')assert(s.sales.some(v=>v.orderId===o.id),'La entrega debe conservar su venta');}
 for(const m of s.money){check(m.amount,false,!!m.reversalOf);assert(m.amount!==0,'El movimiento no puede ser cero');assert(Array.isArray(m.allocations),'Asignación de movimiento inválida');for(const a of m.allocations)check(a.amount,false,!!m.reversalOf);assert(m.allocations.reduce((n,a)=>n+a.amount,0)<=m.amount||!!m.reversalOf,'La asignación excede el importe');for(const a of m.allocations){if(['Cobro','Devolución al cliente'].includes(m.kind))assert(s.orders.some(o=>o.id===a.entityId),'La asignación no corresponde a un pedido');else if(['Pago','Devolución de proveedor'].includes(m.kind))assert(s.purchases.some(p=>p.id===a.entityId),'La asignación no corresponde a una compra');else assert(false,'Este tipo de movimiento no se asigna a pedidos ni compras');}if(m.accountId)assert(s.accounts.some(a=>a.id===m.accountId),'La cuenta del movimiento no existe');if(m.toAccountId)assert(s.accounts.some(a=>a.id===m.toAccountId),'La cuenta de destino no existe');if(m.reversalOf)assert(s.money.some(v=>v.id===m.reversalOf&&!v.reversalOf),'No existe el movimiento original de la corrección');}
 const salesOrders=new Set<string>();for(const v of s.sales){check(v.amount);assert(!salesOrders.has(v.orderId),'Una entrega no puede crear dos ventas');salesOrders.add(v.orderId);assert(s.orders.some(o=>o.id===v.orderId),'No existe el pedido de la venta');for(const a of v.adjustments)check(a.amount,false,true);assert(v.amount+v.adjustments.reduce((n,a)=>n+a.amount,0)>=0,'Los ajustes no pueden dejar una venta negativa');}
 for(const p of s.purchases){check(p.amount);check(p.businessAmount);assert(p.businessAmount<=p.amount,'La parte del negocio excede el gasto total');for(const a of p.adjustments)check(a.amount,false,true);assert(p.businessAmount+p.adjustments.reduce((n,a)=>n+a.amount,0)>=0,'Compra con saldo negativo');assert(p.allocations.reduce((n,a)=>n+a.amount,0)<=p.businessAmount,'El reparto supera la parte del negocio');}
 for(const a of s.accounts)check(a.opening,true,true);
 for(const c of s.clients){assert(c.name.trim(),'El cliente necesita nombre');assert(['Autorizado','No autorizado','No consta'].includes(c.consent),'Consentimiento inválido');if(c.consent==='Autorizado')assert(c.consentEvidence.trim()&&c.consentAt,'Registra cuándo y cómo se autorizó el contacto promocional');}
 for(const t of s.tasks){if(t.purpose==='Novedades/promoción'&&['Pendiente','En curso'].includes(t.status)){const c=s.clients.find(c=>c.id===t.clientId);assert(c?.consent==='Autorizado','Las novedades y promociones requieren autorización del cliente');}}
 for(const c of s.costs){assert(c.yield===null||Number.isFinite(c.yield)&&c.yield>0,'El rendimiento debe ser positivo');assert(c.laborMinutes===null||Number.isFinite(c.laborMinutes)&&c.laborMinutes>=0,'El tiempo de trabajo no puede ser negativo');for(const i of c.ingredients){assert(i.usedQuantity===null||Number.isFinite(i.usedQuantity)&&i.usedQuantity>=0,'La cantidad usada no puede ser negativa');assert(i.purchaseQuantity===null||Number.isFinite(i.purchaseQuantity)&&i.purchaseQuantity>0,'La cantidad comprada debe ser positiva');}for(const part of c.components)assert(Number.isFinite(part.quantity)&&part.quantity>0,'La cantidad del componente debe ser positiva');for(const key of ['packaging','laborHourly','other','overhead'] as const)check(c[key],true);for(const i of c.ingredients)check(i.purchasePrice,true);}
 return s;
}
const ensureReason=(reason:string)=>assert(reason.trim().length>=3,'Escribe el motivo del cambio');
const version=(o:Order,actor:string,at:string,reason:string)=>({at,by:actor,reason,total:o.total,lines:structuredClone(o.lines),scope:structuredClone(o.scope),deliveryDate:o.deliveryDate,paymentTerms:o.paymentTerms,acceptedAt:o.acceptedAt});
export function applyCommand(input:AppState,envelope:CommandEnvelope):AppState {
 if(input.requests.includes(envelope.id))return input;
 assert(input.revision===envelope.expectedStateRevision,'Los datos cambiaron. Actualiza la página y revisa antes de guardar.');
 assert(envelope.actor.trim(),'Falta la identidad de quien guarda');
 let s=structuredClone(input);const c=envelope.command;let before:unknown=null,after:unknown=null,entity='negocio',entityId=s.businessId,reason='';
 const touch=(r:{revision:number;updatedAt:string})=>{r.revision++;r.updatedAt=envelope.at;};
 const getOrder=(oid:string)=>{const o=s.orders.find(o=>o.id===oid);assert(o,'No se encontró el pedido');return o;};
 switch(c.type){
 case 'save':{
  assert(!['money','sales','audit'].includes(c.collection),'Este registro se cambia mediante una operación específica');
  const list=s[c.collection] as unknown as Array<Record<string,unknown>&{id:string;revision:number;updatedAt:string}>;let rec=structuredClone(c.record);const old=list.find(r=>r.id===rec.id);entity=c.collection;entityId=rec.id;before=old?structuredClone(old):null;reason=c.reason||'';
  if(old){assert(c.expectedRevision===undefined||old.revision===c.expectedRevision,'Este registro fue modificado. Revisa la versión actual.');rec.revision=old.revision+1;rec.createdAt=old.createdAt as string;}else rec.revision=1;rec.updatedAt=envelope.at;
  if(c.collection==='orders'){
   const o=rec as unknown as Order;if(old){const prev=old as unknown as Order;const commercial=(r:Order)=>JSON.stringify([r.lines,r.scope,r.deliveryDate,r.deliveryTime,r.transport,r.extra,r.discount,r.paymentTerms,r.changesTerms,r.location,r.modality,r.clientId]);assert(o.status===prev.status,'Utiliza el cambio de estado del pedido');if(commercial(o)!==commercial(prev)){assert(!['Entregado','Cancelado'].includes(prev.status),'Los acuerdos entregados o cancelados conservan sus condiciones. Registra un ajuste por separado.');o.versions=[...prev.versions,version(prev,envelope.actor,envelope.at,reason||'Cambio de condiciones')];if(['Confirmado','En preparación'].includes(prev.status)){o.status='Por confirmar';o.acceptedAt=null;o.acceptedChannel='';o.capacityCheckedAt=null;o.capacityCheckedBy=null;}}o.confirmedAt=prev.confirmedAt;o.deliveredAt=prev.deliveredAt;o.cancelCharge=prev.cancelCharge;o.cancelReason=prev.cancelReason;}else assert(['Borrador','Por confirmar'].includes(o.status),'Primero guarda el pedido y confirma el acuerdo');o.total=orderTotal(o);
  }
  if(c.collection==='products'||c.collection==='options'){const r=rec as unknown as AppState['products'][number];if(old){const prior=old as unknown as typeof r;assert(reason||r.price===prior.price&&r.priceKind===prior.priceKind,'Indica el motivo del nuevo precio');if(JSON.stringify(rec)!==JSON.stringify(old))r.history=[...prior.history,{at:envelope.at,by:envelope.actor,price:prior.price,priceKind:prior.priceKind,description:reason||'Actualización de ficha'}];}if(r.status==='Aprobado')assert(r.price!==null&&r.priceKind==='Aprobado'&&r.approvedBy.includes('Mabel')&&r.approvedBy.includes('Ana'),'La referencia se aprueba con precio definido y revisión de Mabel y Ana');}
  if(c.collection==='clients'){const client=rec as unknown as AppState['clients'][number];if(client.consent!=='Autorizado'){s.tasks.filter(t=>t.clientId===client.id&&t.purpose==='Novedades/promoción'&&['Pendiente','En curso'].includes(t.status)).forEach(t=>{t.status='Cancelada';touch(t);});}}
  if(c.collection==='inquiries'){const q=rec as unknown as AppState['inquiries'][number];if(!old){q.responseDue=responseDeadline(s,q.receivedAt);q.ruleVersion=s.settings.responseHours===null?null:s.settings.ruleVersion;}else{const prev=old as unknown as typeof q;q.responseDue=prev.responseDue;q.ruleVersion=prev.ruleVersion;q.confirmedAt=prev.confirmedAt;}}
  if(c.collection==='purchases'&&old){const prev=old as unknown as AppState['purchases'][number],p=rec as unknown as typeof prev;assert(p.businessAmount===prev.businessAmount&&p.amount===prev.amount&&p.date===prev.date&&p.status===prev.status,'Conserva la compra original y utiliza «Ajustar compra»');p.adjustments=prev.adjustments;}
  if(c.collection==='accounts'&&old&&s.money.some(m=>m.accountId===rec.id||m.toAccountId===rec.id)){assert(rec.opening===old.opening&&rec.openingDate===old.openingDate||old.opening===null&&rec.opening!==null&&!!rec.openingDate&&!!rec.source&&!!reason,'El saldo de apertura con movimientos se conserva. Registra una corrección de saldo.');}
  if(old)list[list.indexOf(old)]=rec;else list.push(rec);after=structuredClone(rec);break;
 }
 case 'settings':before=s.settings;s.settings=structuredClone(c.settings);s.settings.ruleVersion=before&&JSON.stringify([(before as AppState['settings']).responseHours,(before as AppState['settings']).workDays,(before as AppState['settings']).workStart,(before as AppState['settings']).workEnd])!==JSON.stringify([c.settings.responseHours,c.settings.workDays,c.settings.workStart,c.settings.workEnd])?input.settings.ruleVersion+1:input.settings.ruleVersion;after=s.settings;break;
 case 'confirmOrder':{const o=getOrder(c.id);assert(['Borrador','Por confirmar'].includes(o.status),'El pedido ya está confirmado o cerrado');assert(o.lines.length>0&&o.lines.every(l=>l.unitPrice!==null&&l.priceKind==='Aprobado'),'Confirma los precios de todos los productos antes de aceptar el pedido');assert(o.transport!==null,'Confirma el importe de traslado; indica cero si no corresponde');assert(!o.scope.some(x=>x.status==='Adicional cotizado'&&x.amount===null),'Los servicios adicionales necesitan un importe confirmado');assert(o.deliveryDate&&o.paymentTerms.trim()&&o.changesTerms.trim(),'Define fecha, condiciones de pago y cambios');assert(c.acceptedAt&&c.acceptedChannel&&c.capacityChecked,'Registra la aceptación y confirma los recursos disponibles');if(o.modality==='Catering')assert(o.scope.length>=5&&!o.scope.some(x=>x.status==='Por confirmar'),'Define el alcance: alimentos, entrega, montaje, atención y recursos');assert(!o.isSimulation,'Una simulación debe duplicarse como pedido real antes de confirmar');before=structuredClone(o);o.status='Confirmado';o.acceptedAt=c.acceptedAt;o.acceptedChannel=c.acceptedChannel;o.capacityCheckedAt=envelope.at;o.capacityCheckedBy=envelope.actor;o.confirmedAt=o.confirmedAt||c.acceptedAt;touch(o);if(o.inquiryId){const q=s.inquiries.find(q=>q.id===o.inquiryId);if(q){q.status='Con pedido';q.confirmedAt=q.confirmedAt||c.acceptedAt;touch(q);}}after=o;entity='orders';entityId=o.id;break;}
 case 'orderStatus':{const o=getOrder(c.id);assert(c.status==='En preparación'?o.status==='Confirmado':['Borrador','Confirmado','En preparación'].includes(o.status),'Este cambio de estado no corresponde');before=structuredClone(o);o.status=c.status;if(c.status==='Por confirmar'){o.acceptedAt=null;o.capacityCheckedAt=null;}touch(o);after=o;entity='orders';entityId=o.id;break;}
 case 'deliverOrder':{const o=getOrder(c.id);assert(['Confirmado','En preparación'].includes(o.status),'Sólo se entregan pedidos confirmados');assert(!s.sales.some(v=>v.orderId===o.id),'La entrega ya tiene una venta registrada');assert(/^\d{4}-\d{2}-\d{2}$/.test(c.date),'Indica la fecha real de entrega');assert(!o.acceptedAt||c.date>=dateOf(o.acceptedAt),'La entrega no puede preceder la aceptación del acuerdo');before=structuredClone(o);o.status='Entregado';o.deliveredAt=c.date;touch(o);s.sales.push({...base(),revision:1,orderId:o.id,date:c.date,amount:o.total,modality:o.modality,eventId:o.eventId,clientId:o.clientId,adjustments:[]});after=o;entity='orders';entityId=o.id;break;}
 case 'cancelOrder':{const o=getOrder(c.id);ensureReason(c.reason);assert(!['Entregado','Cancelado'].includes(o.status),'Para una entrega utiliza un ajuste comercial, sin borrar la venta');assert(c.charge>=0&&c.charge<=o.total,'La retención acordada debe estar entre cero y el total');before=structuredClone(o);o.versions.push(version(o,envelope.actor,envelope.at,c.reason));o.status='Cancelado';o.cancelReason=c.reason;o.cancelCharge=c.charge;o.cancelledAt=dateOf(envelope.at);touch(o);s.tasks.filter(t=>t.orderId===o.id&&t.status!=='Completada').forEach(t=>{t.status='Cancelada';touch(t);});after=o;entity='orders';entityId=o.id;reason=c.reason;break;}
 case 'adjustOrder':{const o=getOrder(c.id),sale=s.sales.find(v=>v.orderId===o.id);assert(sale,'Los ajustes comerciales corresponden a pedidos entregados');ensureReason(c.reason);assert(c.amount!==0&&Number.isSafeInteger(c.amount),'Indica un ajuste distinto de cero');assert(c.date>=sale.date,'La fecha del ajuste no puede preceder la entrega');assert(sale.amount+sale.adjustments.reduce((n,a)=>n+a.amount,0)+c.amount>=0,'El ajuste excede el valor de la venta');before=structuredClone(sale);sale.adjustments.push({id:id(),amount:c.amount,date:c.date,reason:c.reason,by:envelope.actor});touch(sale);after=sale;entity='sales';entityId=sale.id;reason=c.reason;break;}
 case 'recordMoney':{
  const m=structuredClone(c.record);assert(m.amount>0&&Number.isSafeInteger(m.amount),'Escribe un importe positivo');assert(!m.reversalOf&&!m.reversedBy,'Usa la corrección de movimientos para anular uno existente');assert(!s.money.some(x=>x.id===m.id),'El movimiento ya fue registrado');assert(m.date&&m.method,'Indica la fecha y el medio del movimiento');if(m.accountId)assert(s.accounts.some(a=>a.id===m.accountId&&a.active),'Elige una cuenta activa');
  const dirs:Record<MoneyRecord['kind'],string>={Cobro:'Entrada',Pago:'Salida','Devolución al cliente':'Salida','Devolución de proveedor':'Entrada',Aporte:'Entrada',Retiro:'Salida','Préstamo recibido':'Entrada','Pago de préstamo':'Salida',Transferencia:'Salida','Ajuste de saldo':m.direction};m.direction=dirs[m.kind] as typeof m.direction;
  if(['Cobro','Devolución al cliente','Pago','Devolución de proveedor'].includes(m.kind))assert(m.allocations.length&&m.allocations.reduce((n,a)=>n+a.amount,0)===m.amount,'Asigna todo el importe a sus pedidos o compras');else assert(m.allocations.length===0,'Este movimiento no se asigna a pedidos ni compras');
  assert(new Set(m.allocations.map(a=>a.entityId)).size===m.allocations.length,'No repitas un pedido o compra en el reparto');
  for(const a of m.allocations){assert(a.amount>0,'Los importes asignados deben ser positivos');if(['Cobro','Devolución al cliente'].includes(m.kind)){const o=getOrder(a.entityId);assert(o.confirmedAt&&!o.isSimulation,'El cobro requiere un pedido confirmado');assert(m.date>=dateOf(o.confirmedAt),'La fecha del cobro no puede preceder la confirmación');const balance=orderBalance(s,o);if(m.kind==='Cobro')assert(c.allowCredit||a.amount<=Math.max(0,balance),'El cobro excede el saldo. Confirma explícitamente el saldo a favor');else assert(a.amount<=Math.max(0,-balance),'La devolución excede el saldo a favor; registra primero el ajuste o cancelación acordados');}else {const p=s.purchases.find(p=>p.id===a.entityId);assert(p,'Elige una compra registrada');assert(m.date>=p.date,'La fecha del pago no puede preceder la compra');const balance=purchaseBalance(s,p);if(m.kind==='Pago')assert(c.allowCredit||a.amount<=Math.max(0,balance),'El pago excede el saldo de la compra');else assert(a.amount<=Math.max(0,-balance),'La devolución del proveedor excede el saldo a favor');}}
  if(m.kind==='Transferencia')assert(m.accountId&&m.toAccountId&&m.accountId!==m.toAccountId&&s.accounts.some(a=>a.id===m.toAccountId&&a.active),'Selecciona dos cuentas distintas y activas');if(m.kind==='Ajuste de saldo')assert(m.accountId&&m.notes.trim(),'Indica la cuenta y el motivo de la corrección');m.requestId=envelope.id;m.revision=1;m.updatedAt=envelope.at;s.money.push(m);after=m;entity='money';entityId=m.id;break;
 }
 case 'reverseMoney':{ensureReason(c.reason);const m=s.money.find(m=>m.id===c.id);assert(m&&!m.reversedBy&&!m.reversalOf,'El movimiento no existe o ya fue corregido');assert(c.date>=m.date,'La corrección no puede preceder al movimiento original');before=structuredClone(m);const reversal:MoneyRecord={...structuredClone(m),...base(),revision:1,amount:-m.amount,allocations:m.allocations.map(a=>({...a,amount:-a.amount})),date:c.date,notes:c.reason,reversalOf:m.id,reversedBy:null,requestId:envelope.id};m.reversedBy=reversal.id;touch(m);s.money.push(reversal);after=reversal;entity='money';entityId=m.id;reason=c.reason;break;}
 case 'assignAccount':{const m=s.money.find(m=>m.id===c.id);assert(m&&!m.accountId&&!m.reversalOf&&!m.reversedBy,'Sólo se asigna una vez una cuenta pendiente');assert(s.accounts.some(a=>a.id===c.accountId&&a.active),'Elige una cuenta activa');before=structuredClone(m);m.accountId=c.accountId;touch(m);after=m;entity='money';entityId=m.id;break;}
 case 'purchaseAdjustment':{ensureReason(c.reason);const p=s.purchases.find(p=>p.id===c.id);assert(p,'No se encontró la compra');assert(c.date>=p.date,'La fecha del ajuste no puede preceder la compra');before=structuredClone(p);const current=p.businessAmount+p.adjustments.reduce((n,a)=>n+a.amount,0);assert(!c.cancel||p.status!=='Cancelada','La compra ya fue cancelada');const amount=c.cancel?-current:c.amount;assert(current+amount>=0&&Number.isSafeInteger(amount),'El ajuste deja un importe inválido');p.adjustments.push({amount,date:c.date,reason:c.reason});if(c.cancel)p.status='Cancelada';touch(p);after=p;entity='purchases';entityId=p.id;reason=c.reason;break;}
 case 'mergeClients':{ensureReason(c.reason);const keep=s.clients.find(x=>x.id===c.keepId),remove=s.clients.find(x=>x.id===c.removeId);assert(keep&&remove&&keep.id!==remove.id&&!remove.mergedInto,'Elige dos clientes distintos y vigentes');before=[structuredClone(keep),structuredClone(remove)];for(const k of ['inquiries','orders','tasks','sales','interactions','conversations'] as const){for(const r of s[k])if(r.clientId===remove.id){r.clientId=keep.id;touch(r);}}keep.notes=[keep.notes,`Registro combinado de ${remove.name}: ${remove.notes}`].filter(Boolean).join('\n');if(keep.consent!=='Autorizado'||remove.consent!=='Autorizado'){keep.consent=keep.consent==='No autorizado'||remove.consent==='No autorizado'?'No autorizado':'No consta';keep.consentEvidence='';keep.consentAt='';s.tasks.filter(t=>t.clientId===keep.id&&t.purpose==='Novedades/promoción').forEach(t=>{t.status='Cancelada';});}remove.mergedInto=keep.id;remove.archived=true;touch(keep);touch(remove);after=[keep,remove];entity='clients';entityId=keep.id;reason=c.reason;break;}
 case 'restore':{ensureReason(c.reason);const restored=structuredClone(validateState(c.state));assert(restored.businessId===s.businessId||s.revision===0&&!s.orders.length&&!s.money.length&&!s.audit.length,'La copia pertenece a otro negocio. Cárgala en su repositorio correspondiente');before={revision:s.revision};restored.revision=s.revision;restored.audit=[...s.audit];restored.requests=[...s.requests];s=restored;after={sourceRevision:c.state.revision};reason=c.reason;break;}
 case 'clientFromInquiry':{const inquiry=s.inquiries.find(q=>q.id===c.inquiryId);assert(inquiry&&!inquiry.clientId,'La consulta ya tiene cliente o no existe');const first=applyCommand(s,{...envelope,id:envelope.id+':client',command:{type:'save',collection:'clients',record:c.client as unknown as import('./types').Base & Record<string,unknown>}});s=first;const q=s.inquiries.find(q=>q.id===c.inquiryId)!;q.clientId=c.client.id;q.contactName=c.client.name;touch(q);s.audit=[...input.audit];after={client:c.client,inquiry:q};entity='clients';entityId=c.client.id;break;}
 case 'purchaseWithNeed':{const need=s.purchaseNeeds.find(n=>n.id===c.needId);assert(need,'La necesidad de compra no existe');assert(c.quantity>0&&Number.isFinite(c.quantity)&&c.purchase.unit===need.unit,'Revisa la cantidad real y la unidad de compra');assert(!s.purchases.some(p=>p.id===c.purchase.id),'La compra ya fue registrada');s=applyCommand(s,{...envelope,id:envelope.id+':purchase',command:{type:'save',collection:'purchases',record:c.purchase as unknown as import('./types').Base & Record<string,unknown>}});const n=s.purchaseNeeds.find(n=>n.id===c.needId)!;n.purchased+=c.quantity;n.purchaseId=c.purchase.id;touch(n);s.audit=[...input.audit];after={purchase:c.purchase,need:n};entity='purchases';entityId=c.purchase.id;break;}
 case 'fairSale':{assert(!s.orders.some(o=>o.id===c.order.id),'Esta venta de feria ya existe');assert(c.order.eventId&&s.fairs.some(f=>f.id===c.order.eventId&&!f.closed),'Selecciona una feria abierta');const event=s.fairs.find(f=>f.id===c.order.eventId)!;assert(event.date===c.date,'La fecha debe coincidir con la feria');const nested=(command:CommandEnvelope['command'],suffix:string)=>{s=applyCommand(s,{...envelope,id:envelope.id+suffix,expectedStateRevision:s.revision,command});};nested({type:'save',collection:'orders',record:c.order as unknown as import('./types').Base & Record<string,unknown>},':order');nested({type:'confirmOrder',id:c.order.id,acceptedAt:c.acceptedAt,acceptedChannel:'Presencial',capacityChecked:true},':confirm');nested({type:'deliverOrder',id:c.order.id,date:c.date},':deliver');if(c.received)nested({type:'recordMoney',record:c.received},':money');s.audit=[...input.audit];after=s.orders.find(o=>o.id===c.order.id);entity='fairs';entityId=event.id;break;}
 case 'splitOrder':{const o=getOrder(c.id);assert(!['Entregado','Cancelado'].includes(o.status),'No se divide un pedido cerrado');ensureReason(c.reason);assert(c.parts.length>=2,'Crea al menos dos entregas');assert(c.parts.every(p=>p.modality===o.modality&&p.clientId===o.clientId&&p.inquiryId===o.inquiryId),'Las entregas deben conservar cliente, consulta y tipo');assert(c.parts.reduce((n,p)=>n+orderTotal(p),0)===o.total,'El total de las entregas debe coincidir con el pedido original');before=structuredClone(o);for(const part of c.parts){assert(!s.orders.some(x=>x.id===part.id),'La entrega ya existe');part.parentId=o.id;part.splitEffectiveDate=dateOf(envelope.at);part.total=orderTotal(part);part.status='Por confirmar';part.confirmedAt=o.confirmedAt;part.acceptedAt=null;part.acceptedChannel='';part.capacityCheckedAt=null;part.capacityCheckedBy=null;part.revision=1;s.orders.push(part);}for(const m of s.money){const allocations=m.allocations.filter(a=>a.entityId===o.id);if(allocations.length)m.allocationHistory=[...(m.allocationHistory||[]),{date:dateOf(envelope.at),before:structuredClone(m.allocations)}];for(const a of allocations){const total=a.amount;let remainder=total;const shares=c.parts.map((p,i)=>{const amount=i===c.parts.length-1?remainder:Math.round(total*p.total/o.total);remainder-=amount;return{entityId:p.id,amount};});m.allocations=m.allocations.filter(x=>x!==a).concat(shares.filter(x=>x.amount!==0));}}o.status='Cancelado';o.cancelReason='Dividido en entregas; importes reasignados';o.cancelCharge=0;o.cancelledAt=dateOf(envelope.at);o.versions.push(version(o,envelope.actor,envelope.at,c.reason));touch(o);after=c.parts;entity='orders';entityId=o.id;reason=c.reason;break;}
 }
 s.requests.push(envelope.id);s.revision=input.revision+1;s.updatedAt=envelope.at;s.audit.push({...base(),revision:1,createdAt:envelope.at,updatedAt:envelope.at,actor:envelope.actor,action:c.type,entity,entityId,reason,before,after:structuredClone(after)});return validateState(s);
}
