import type {AppState,Product,Order,OrderLine,Client,Inquiry,MoneyRecord} from './types';
import {base,id,iso,today} from './helpers';
import {orderTotal} from './selectors';
const sourceHash='e732ab433808cf0baaccd79c6deda0513269b657288b73f91f4a43e889d94b51';
function product(name:string,family:string,page:number,price:number|null=null,unit='unidad',baseQuantity=1,attributes:Partial<Product['attributes']>={}):Product {return {...base(),name,family,description:'',culturalDescription:'',ingredients:'',allergens:'',conservation:'',attributes:{filling:'',cacao:'',shape:'',size:'',coverage:'',decoration:'',presentation:'',...attributes},variants:[],unit,baseQuantity,price,priceKind:price===null?'Consultar':'Publicado por confirmar',sourcePage:page,sourceDocument:'Catálogo preliminar Mabell Ramos (14 páginas)',sourceHash,status:'Por revisar',priority:false,available:'Por confirmar con Mabel',preparationMinutes:null,validFrom:'',approvedBy:[],photo:family==='Chocotejas'?'assets/chocotejas.png':family==='Alfajores'?'assets/alfajores.png':'',notes:'El precio publicado y los atributos se conservan como referencia. Revisar disponibilidad y condiciones antes de aprobar.',history:[]};}
export function catalogProducts():Product[]{const products:Product[]=[];const fillings:[string,number,number][]=[['Lúcuma',350,800],['Maracuyá',350,800],['Pistachos y frambuesa',350,800],['Pecanas',350,800],['Higos',300,600],['Pasas',300,600],['Guindón',300,600],['Manjar de pallar',350,800],['Frejol colado',350,800],['Ají',400,800],['Pie de limón',350,800],['Chocomaní',350,800],['Café',350,800]];for(const [filling,p18,p40] of fillings){for(const [cacao,price] of [['18 %',p18],['40 %',p40]] as const)products.push(product(`Chocoteja de ${filling.toLowerCase()} · ${cacao}`,'Chocotejas',2,price,'unidad',1,{filling,cacao}));}
products.push(product('Chocotejas en forma de flor','Chocotejas',2,null,'unidad',1,{shape:'Flor'}));
for(const v of ['Clásico','Cañihua','Lúcuma','Chocochips','Pistacho y arándano','Manjar de pistacho','Anís y canela']){const p=product(`Alfajor · ${v}`,'Alfajores',3);p.variants=['Circular','Corazón'];p.notes+=' La combinación de masa, relleno y forma se define al revisar la ficha.';products.push(p);}
for(const v of ['Lúcuma','Kiwi deshidratado','Manjar blanco','Frutos secos','Arándano']){const p=product(`Bombón · ${v}`,'Bombones',4,null,'unidad',1,{filling:v});p.variants=['Mármol','Corazón','Dorado','Flores','Papel de oro'];products.push(p);}
for(const v of ['Pecanas','Pecanas y avena'])products.push(product(`Trufa · ${v}`,'Trufas',5,null,'unidad',1,{filling:v}));
for(const size of ['Grande','Pequeña']){const p=product(`Dona · ${size.toLowerCase()}`,'Donas',5,null,'unidad',1,{size});p.variants=['Relleno de manjar','Relleno de mermelada','Cobertura bitter','Cobertura de leche','Cobertura blanca','Cobertura de colores'];products.push(p);}
for(const [n,page,price] of [['Chocoteja tamaño bocadito',7,11500],['Tartaleta dulce',7,11000],['Trufa tamaño bocadito',7,10000],['Cheesecake tamaño bocadito',7,9500],['Mini pie de limón',8,11000],['Mini pie de maracuyá',8,11000],['Mini pie de Oreo',8,null],['Alfajor tamaño bocadito',8,8000],['Mini pizza clásica',9,10500],['Mini pizza hawaiana',9,10500],['Mini pizza tres quesos',9,10500],['Mini pizza pepperoni',9,10500],['Mini pizza cabanosi',9,10500],['Petit pan con pollo',9,10500],['Mini hamburguesa',9,10500],['Mini causita',10,12500],['Triple vegano tamaño bocadito',10,12500],['Triple tamaño bocadito',10,10000],['Tartaleta de ají de pollo',10,12500]] as [string,number,number|null][]){products.push(product(n,n.includes('pizza')||page===9||page===10?'Bocaditos salados':'Bocaditos dulces',page,price,'unidad',100,{size:'Bocadito'}));}
for(const [n,price] of [['Triple personal de aceituna, palta o pollo',80000],['Croissant personal',60000],['Triple personal de jamón o pollo',80000],['Hamburguesa personal',100000]] as const)products.push(product(n,'Porciones personales',11,price,'unidad',100,{size:'Porción personal'}));
for(const n of ['Café','Chicha','Bebida de maracuyá'])products.push(product(n,'Bebidas',12,null,'botella',1,{presentation:'Capacidad por confirmar'}));
for(const [n,price] of [['Cupcake personalizado',700],['Cake pop personalizado',500]] as const){const p=product(n,'Personalizados',13,price);p.priceKind='Referencial';products.push(p);}
return products;}
export function createEmptyState():AppState{return {schemaVersion:1,revision:0,updatedAt:iso(),businessId:id(),settings:{businessName:'Mabell Ramos',currency:'PEN',timezone:'America/Lima',startDate:today(),responseHours:null,workStart:9,workEnd:18,workDays:[1,2,3,4,5,6],ruleVersion:0,methods:[],categories:['Insumos','Empaque','Traslado','Alquiler','Servicio','Otro'],catalogUrl:'https://gsaco.github.io/Mabell-Ramos/#pagina-3',originalPdfUrl:'https://github.com/gsaco/Mabell-Ramos/raw/refs/heads/main/Entregables/catalogo.pdf',standUrl:'https://github.com/gsaco/Mabell-Ramos/blob/main/Entregables/stand.pdf',phone:'',instagram:'',profiles:[{name:'Mabel',githubLogin:''},{name:'Ana',githubLogin:''}],onboardingDone:false},clients:[],inquiries:[],products:catalogProducts(),options:[],orders:[],tasks:[],purchaseNeeds:[],purchases:[],suppliers:[],money:[],accounts:[],sales:[],costs:[],fairs:[],interactions:[],conversations:[],publications:[],attachments:[],closings:[],reconciliations:[],audit:[],requests:[]};}
export function blankOrder(state:AppState):Order{return{...base(),code:`MR-${String(state.orders.length+1).padStart(4,'0')}`,clientId:null,contactName:'',inquiryId:null,modality:'Productos',need:'Por conocer',status:'Borrador',responsible:'Ana',deliveryDate:'',deliveryTime:'',location:'',deliveryMode:'Retiro',lines:[],scope:[],attendees:null,duration:'',eventId:null,parentId:null,transport:null,extra:0,discount:0,total:0,paymentTerms:'',changesTerms:'',customerNotes:'',internalNotes:'',acceptedAt:null,acceptedChannel:'',capacityCheckedAt:null,capacityCheckedBy:null,confirmedAt:null,deliveredAt:null,dueDate:'',cancelReason:'',cancelCharge:0,versions:[],costEstimate:null,costReviewed:false,costRevision:0,isSimulation:false};}
export function createDemoState():AppState{const s=createEmptyState();s.businessId='mabell-ramos-demo';s.settings={...s.settings,startDate:'2026-08-01',responseHours:4,workStart:9,workEnd:18,workDays:[1,2,3,4,5,6],ruleVersion:1,methods:['Efectivo','Transferencia','Yape'],onboardingDone:true};
const makeClient=(name:string,origin:string,consent:Client['consent']='No consta'):Client=>({...base(),name,type:'Persona',phone:'',email:'',instagram:'',origin,originEvidence:'Ejemplo ficticio para aprender a usar la aplicación',preferredChannel:'WhatsApp',contacts:[],preferences:'',preferencesSource:'',consent,consentEvidence:consent==='Autorizado'?'Autorización ficticia registrada en la demostración':'',consentAt:consent==='Autorizado'?'2026-09-01':'',notes:'Datos ficticios. No corresponde a una persona real.'});
s.clients=[makeClient('Lucía · ejemplo','Feria','Autorizado'),makeClient('Carlos · ejemplo','Recomendación'),makeClient('Elena · ejemplo','Institución'),makeClient('Rosa · ejemplo','Instagram'),makeClient('José · ejemplo','Feria')];
s.accounts=[{...base(),name:'Caja de ejemplo',opening:0,openingDate:'2026-08-01',source:'Saldo ficticio para la demostración',active:true}];
const demoProducts=[['Alfajores clásicos · ejemplo',1000],['Caja regalo · ejemplo',3000],['Bocaditos · ejemplo',600]] as const;for(const [name,price] of demoProducts){const p=product(name,'Ejemplo ficticio',0,price);p.status='Aprobado';p.priceKind='Aprobado';p.approvedBy=['Mabel','Ana'];p.priority=true;p.available='Disponible en la demostración';s.products.push(p);}
const refs=s.products.filter(p=>p.family==='Ejemplo ficticio');
const makeOrder=(client:number,total:number,date:string,delivered:boolean,modality:'Productos'|'Catering'='Productos',cost:number|null=null):Order=>{const o=blankOrder(s);o.code=`MR-${String(s.orders.length+1).padStart(4,'0')}`;o.clientId=s.clients[client].id;o.contactName=s.clients[client].name;o.modality=modality;o.need=modality==='Catering'?'Reunión/evento':client===1||client===3?'Regalo':'Consumo y recompra';o.status=delivered?'Entregado':'Confirmado';o.deliveryDate=date;o.total=total;o.transport=0;o.paymentTerms='Importe y forma de pago acordados para este ejemplo';o.changesTerms='Cambios sujetos a disponibilidad y nueva aceptación';o.acceptedAt='2026-09-01T15:00:00Z';o.acceptedChannel='WhatsApp';o.capacityCheckedAt=o.acceptedAt;o.capacityCheckedBy='Ana · demostración';o.confirmedAt='2026-09-01T15:00:00Z';o.deliveredAt=delivered?date:null;o.costEstimate=cost;o.costReviewed=cost!==null;o.lines=[{id:id(),referenceId:refs[0].id,referenceType:'product',name:modality==='Catering'?'Alimentos para reunión · ejemplo':'Selección de productos · ejemplo',quantity:1,unit:'lote',unitsPerPack:1,baseQuantity:1,unitPrice:total,priceKind:'Aprobado',attributes:'Condiciones ficticias para probar',distribution:[],sourceVersion:1,costVersionId:null,notes:''}];if(modality==='Catering')o.scope=['Alimentos','Entrega','Montaje','Atención','Menaje'].map(name=>({name,status:name==='Alimentos'?'Incluido':'No incluido',detail:'Alcance acordado en este ejemplo',amount:0,responsible:'Ana'}));s.orders.push(o);if(delivered)s.sales.push({...base(),orderId:o.id,date,amount:total,modality,eventId:null,clientId:o.clientId,adjustments:[]});return o;};
const orders=[makeOrder(0,10000,'2026-09-05',true,'Productos',6000),makeOrder(1,18000,'2026-09-07',true,'Productos',9000),makeOrder(2,60000,'2026-09-12',true,'Catering',42000),makeOrder(3,24000,'2026-09-20',false)];
makeOrder(0,5000,'2026-08-20',true);makeOrder(2,10000,'2026-08-22',true);for(const o of s.orders.filter(o=>o.deliveryDate<'2026-09-01')){o.confirmedAt='2026-08-15T15:00:00Z';o.acceptedAt=o.confirmedAt;}
const makeMoney=(o:Order,amount:number,date:string):MoneyRecord=>({...base(),kind:'Cobro',amount,date,accountId:s.accounts[0].id,toAccountId:null,method:'Transferencia',reference:'DEMOSTRACIÓN',notes:'Cobro ficticio',allocations:[{entityId:o.id,amount}],reversalOf:null,reversedBy:null,direction:'Entrada',requestId:id()});s.money=[makeMoney(orders[0],10000,'2026-09-05'),makeMoney(orders[1],18000,'2026-09-07'),makeMoney(orders[2],40000,'2026-09-10'),makeMoney(orders[3],12000,'2026-09-11'),...s.orders.filter(o=>o.deliveryDate<'2026-09-01').map(o=>makeMoney(o,o.total,o.deliveryDate))];
for(let i=0;i<6;i++){const confirmed=i<4;const client=i===5?0:i<5?i:0;const q:Inquiry={...base(),clientId:s.clients[client].id,contactName:s.clients[client].name,contact:'',summary:confirmed?'Consulta ficticia que dio lugar a un pedido':'Consulta pendiente de seguimiento',modality:i===2?'Catering':'Productos',need:i===2?'Reunión/evento':i===1||i===3?'Regalo':'Consumo y recompra',needSource:'Conversación ficticia',channel:i===4?'Presencial':'WhatsApp',receivedAt:`2026-09-${String(i+1).padStart(2,'0')}T15:00:00Z`,respondedAt:i<4?`2026-09-${String(i+1).padStart(2,'0')}T16:00:00Z`:null,responseDue:`2026-09-${String(i+1).padStart(2,'0')}T19:00:00Z`,ruleVersion:1,requestedDate:'',responsible:'Ana',status:confirmed?'Con pedido':'Por responder',waitingClient:false,nextAction:'Confirmar presentación y fecha',actionDate:'2026-09-29',reason:'',confirmedAt:confirmed?'2026-09-10T15:00:00Z':null};s.inquiries.push(q);if(confirmed)orders[i].inquiryId=q.id;}
s.tasks=[{...base(),title:'Preparar selección para Rosa · ejemplo',date:'2026-09-29',time:'10:00',minutes:90,responsible:'Mabel',collaborator:'',orderId:orders[3].id,clientId:orders[3].clientId,eventId:null,kind:'Preparación',status:'Pendiente',resource:'Cocina',resourceStatus:'Confirmado',purpose:'Atender solicitud/pedido',notes:'Tarea ficticia para conocer la agenda',result:''},{...base(),title:'Responder a José · ejemplo',date:'2026-09-29',time:'09:30',minutes:15,responsible:'Ana',collaborator:'',orderId:null,clientId:s.clients[4].id,eventId:null,kind:'Seguimiento',status:'Pendiente',resource:'',resourceStatus:'No aplica',purpose:'Atender solicitud/pedido',notes:'Seguimiento de una consulta, sin mensaje automático',result:''}];
s.purchaseNeeds=[{...base(),name:'Chocolate · ejemplo',quantity:2,unit:'kg',date:'2026-09-29',responsible:'Ana',orderIds:[orders[3].id],supplier:'Por confirmar',purchased:0,purchaseId:null,notes:'Revisión de compra ficticia'}];
return s;}
