import Decimal from 'decimal.js';
import type {Account,AppState,CostSheet,MoneyRecord,Order,Purchase} from './types';
import {dateOf,inPeriod} from './helpers';
const round=(n:Decimal)=>n.toDecimalPlaces(0,Decimal.ROUND_HALF_UP).toNumber();
export function orderTotal(order:Order){const food=order.lines.reduce((sum,l)=>sum.plus(new Decimal(l.unitPrice??0).times(l.quantity).div(l.baseQuantity||1)),new Decimal(0));const scope=order.scope.filter(s=>s.status==='Adicional cotizado').reduce((sum,s)=>sum+(s.amount??0),0);return round(food.plus(scope).plus(order.transport??0).plus(order.extra).minus(order.discount));}
export function activeMoney(state:AppState,cutoff?:string):MoneyRecord[]{return state.money.filter(m=>!cutoff||dateOf(m.date)<=cutoff);}
export function allocationsAt(m:MoneyRecord,cutoff?:string){let a=m.allocations;if(cutoff)for(const h of [...(m.allocationHistory||[])].sort((a,b)=>b.date.localeCompare(a.date)))if(h.date>cutoff)a=h.before;return a;}
export function applied(state:AppState,entityId:string,kinds:MoneyRecord['kind'][],cutoff?:string){return activeMoney(state,cutoff).filter(m=>kinds.includes(m.kind)).reduce((sum,m)=>sum+allocationsAt(m,cutoff).filter(a=>a.entityId===entityId).reduce((s,a)=>s+a.amount,0),0);}
export function obligation(state:AppState,order:Order,cutoff?:string){const adjustments=state.sales.filter(s=>s.orderId===order.id).flatMap(s=>s.adjustments).filter(a=>!cutoff||a.date<=cutoff).reduce((s,a)=>s+a.amount,0);const oldVersion=cutoff?[...order.versions].filter(v=>dateOf(v.at)>cutoff).sort((a,b)=>a.at.localeCompare(b.at))[0]:null;return (order.status==='Cancelado'&&(!cutoff||!order.cancelledAt||order.cancelledAt<=cutoff)?order.cancelCharge:oldVersion?.total??order.total)+adjustments;}
export function orderBalance(state:AppState,order:Order,cutoff?:string){return obligation(state,order,cutoff)-applied(state,order.id,['Cobro'],cutoff)+applied(state,order.id,['Devolución al cliente'],cutoff);}
export function purchaseBalance(state:AppState,p:Purchase,cutoff?:string){return p.businessAmount+p.adjustments.filter(a=>!cutoff||a.date<=cutoff).reduce((s,a)=>s+a.amount,0)-applied(state,p.id,['Pago'],cutoff)+applied(state,p.id,['Devolución de proveedor'],cutoff);}
export function accountBalance(state:AppState,account:Account,cutoff?:string){if(account.opening===null)return null;let total=account.opening;for(const m of activeMoney(state,cutoff)){if(m.date<account.openingDate)continue; if(m.kind==='Transferencia'){if(m.accountId===account.id)total-=m.amount;if(m.toAccountId===account.id)total+=m.amount;}else if(m.accountId===account.id)total+=m.direction==='Entrada'?m.amount:-m.amount;}return total;}
const units:Record<string,{dimension:string;factor:number}>={g:{dimension:'mass',factor:1},kg:{dimension:'mass',factor:1000},ml:{dimension:'volume',factor:1},L:{dimension:'volume',factor:1000},unidad:{dimension:'count',factor:1},docena:{dimension:'count',factor:12}};
export function convertQuantity(value:number,from:string,to:string){if(from===to)return value;const a=units[from],b=units[to];if(!a||!b||a.dimension!==b.dimension)throw new Error(`No se puede convertir ${from} a ${to} sin un factor validado`);return new Decimal(value).times(a.factor).div(b.factor).toNumber();}
export function costTotal(state:AppState,sheet:CostSheet,visited=new Set<string>()):{total:number|null;unit:number|null;complete:boolean;missing:string[]}{const missing:string[]=[];if(visited.has(sheet.id))return{total:null,unit:null,complete:false,missing:['Hay una referencia circular entre costos']};visited.add(sheet.id);let sum=new Decimal(0);for(const i of sheet.ingredients){if(i.usedQuantity===null||i.purchaseQuantity===null||i.purchasePrice===null||i.purchaseQuantity<=0){missing.push(`Cantidades o precio de ${i.name||'un ingrediente'}`);continue;}try{sum=sum.plus(new Decimal(convertQuantity(i.usedQuantity,i.usedUnit,i.purchaseUnit)).div(i.purchaseQuantity).times(i.purchasePrice));}catch(e){missing.push((e as Error).message);}}
for(const c of sheet.components){const ref=state.costs.find(x=>x.id===c.costSheetId);if(!ref){missing.push('Costo del producto incluido');continue;}const v=costTotal(state,ref,new Set(visited));if(v.unit===null||!v.complete)missing.push(...v.missing);else sum=sum.plus(new Decimal(v.unit).times(c.quantity));}
for(const [key,label] of [['packaging','Empaque'],['other','Otros costos'],['overhead','Gastos repartidos']] as const){if(sheet[key]===null)missing.push(label);else sum=sum.plus(sheet[key]!);}
if(sheet.overhead&& !sheet.overheadMethod)missing.push('Método de reparto de gastos');if(sheet.laborMinutes===null||sheet.laborHourly===null)missing.push('Trabajo por valorar');else sum=sum.plus(new Decimal(sheet.laborMinutes).div(60).times(sheet.laborHourly));if(sheet.yield===null||sheet.yield<=0)missing.push('Rendimiento vendible');if(!sheet.reviewed)missing.push('Revisión del costo');const total=missing.length?null:round(sum);return{total,unit:total===null||!sheet.yield?null:round(new Decimal(total).div(sheet.yield)),complete:missing.length===0,missing:[...new Set(missing)]};}
export function netMoney(state:AppState,kind:MoneyRecord['kind'],from:string,to:string){return state.money.filter(m=>m.kind===kind&&inPeriod(m.date,from,to)).reduce((s,m)=>s+m.amount,0);}
export function financialSummary(state:AppState,from:string,to:string){const delivered=state.sales.filter(s=>inPeriod(s.date,from,to));const sales=delivered.reduce((sum,s)=>sum+s.amount,0)+state.sales.flatMap(s=>s.adjustments).filter(a=>inPeriod(a.date,from,to)).reduce((sum,a)=>sum+a.amount,0);const receipts=netMoney(state,'Cobro',from,to),refunds=netMoney(state,'Devolución al cliente',from,to),payments=netMoney(state,'Pago',from,to),providerRefunds=netMoney(state,'Devolución de proveedor',from,to);const eligible=state.orders.filter(o=>!o.isSimulation&&(!o.splitEffectiveDate||o.splitEffectiveDate<=to)&&o.confirmedAt&&dateOf(o.confirmedAt)<=to);const due=eligible.map(o=>({order:o,value:orderBalance(state,o,to)}));const receivable=due.reduce((s,x)=>s+Math.max(0,x.value),0),credit=due.reduce((s,x)=>s+Math.max(0,-x.value),0);const deliveredDue=due.filter(x=>x.order.deliveredAt&&x.order.deliveredAt<=to).reduce((s,x)=>s+Math.max(0,x.value),0);const payable=state.purchases.filter(p=>p.date<=to).reduce((s,p)=>s+Math.max(0,purchaseBalance(state,p,to)),0);const reviewed=delivered.filter(s=>{const o=state.orders.find(o=>o.id===s.orderId);return o?.costReviewed&&o.costEstimate!==null;});const estimated=reviewed.reduce((sum,s)=>{const o=state.orders.find(o=>o.id===s.orderId)!;return sum+s.amount+s.adjustments.filter(a=>inPeriod(a.date,from,to)).reduce((z,a)=>z+a.amount,0)-(o.costEstimate??0);},0);const advances=state.money.filter(m=>m.kind==='Cobro'&&inPeriod(m.date,from,to)).reduce((sum,m)=>sum+allocationsAt(m,to).filter(a=>{const o=state.orders.find(o=>o.id===a.entityId);return o&&(!o.deliveredAt||o.deliveredAt>to)&&!(o.status==='Cancelado'&&(!o.cancelledAt||o.cancelledAt<=to));}).reduce((z,a)=>z+a.amount,0),0);return{sales,receipts,payments,refunds,providerRefunds,net:receipts-refunds-payments+providerRefunds,receivable,payable,credit,deliveredDue,futureDue:receivable-deliveredDue,estimated,reviewedCount:reviewed.length,deliveredCount:delivered.length,advances};}
export function commercialSummary(state:AppState,from:string,to:string){const inquiries=state.inquiries.filter(i=>inPeriod(i.receivedAt,from,to)&&i.status!=='Duplicada');const confirmed=inquiries.filter(i=>i.confirmedAt&&dateOf(i.confirmedAt)<=to);const evaluable=inquiries.filter(i=>i.responseDue&&(i.respondedAt&&dateOf(i.respondedAt)<=to||dateOf(i.responseDue)<=to));const ontime=evaluable.filter(i=>i.respondedAt&&dateOf(i.respondedAt)<=to&&i.respondedAt<=i.responseDue!);const sales=state.sales.filter(s=>s.clientId&&inPeriod(s.date,from,to));const customers=[...new Set(sales.map(s=>s.clientId!))];const previous=customers.filter(c=>state.sales.some(s=>s.clientId===c&&s.date<from));const group=(field:'channel'|'origin')=>{const counts:Record<string,number>={};for(const i of inquiries){const key=field==='channel'?i.channel:state.clients.find(c=>c.id===i.clientId)?.origin||'No conocido';counts[key]=(counts[key]||0)+1;}return Object.entries(counts).map(([label,value])=>({label,value}));};return{inquiryIds:inquiries.map(i=>i.id),confirmedIds:confirmed.map(i=>i.id),evaluableIds:evaluable.map(i=>i.id),previousClientIds:previous,inquiries:inquiries.length,confirmed:confirmed.length,evaluable:evaluable.length,ontime:ontime.length,clients:customers.length,previous:previous.length,channels:group('channel'),origins:group('origin')};}
export function responseDeadline(state:AppState,receivedAt:string):string|null{const {responseHours,workStart,workEnd,workDays}=state.settings;if(responseHours===null||responseHours<=0||workEnd<=workStart||!workDays.length)return null;let remaining=Math.round(responseHours*60);let cursor=new Date(receivedAt);for(let n=0;n<525600;n++){const local=new Date(cursor.getTime()-5*3600000);const minute=local.getUTCHours()*60+local.getUTCMinutes();if(workDays.includes(local.getUTCDay())&&minute>=workStart*60&&minute<workEnd*60){if(remaining===0)return cursor.toISOString();remaining--;}cursor=new Date(cursor.getTime()+60000);}return null;}
