import type {AppState,Collection,Order} from '../domain/types';
import {money,dateLabel,iso} from '../domain/helpers';
import {financialSummary,orderBalance} from '../domain/selectors';
let attachmentReader:((path:string)=>Promise<Blob>)|null=null;
export const setAttachmentReader=(fn:typeof attachmentReader)=>{attachmentReader=fn;};
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export const downloadBackup=(state:AppState)=>download(new Blob([JSON.stringify({format:'Mabell Ramos',exportedAt:iso(),state},null,2)],{type:'application/json'}),`mabell-ramos-copia-${state.updatedAt.slice(0,10)}.json`);
const csvCell=(v:unknown)=>{let text=typeof v==='object'?JSON.stringify(v):String(v??'');if(typeof v==='string'&&/^[\s]*[=+\-@\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};
export function exportCsv(state:AppState,collection:Collection){const records=state[collection] as unknown as Record<string,unknown>[];const keys=[...new Set(records.flatMap(r=>Object.keys(r)))];const csv=[keys.map(csvCell).join(','),...records.map(r=>keys.map(k=>csvCell(r[k])).join(','))].join('\r\n');download(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}),`mabell-ramos-${collection}.csv`);}
export async function exportBundle(state:AppState){const {default:JSZip}=await import('jszip');const zip=new JSZip();zip.file('datos.json',JSON.stringify({format:'Mabell Ramos',exportedAt:iso(),state},null,2));const manifest=[];for(const a of state.attachments){if(!attachmentReader)throw new Error('Conecta el repositorio para exportar también sus adjuntos');const blob=await attachmentReader(a.path);const bytes=await blob.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');if(hash!==a.hash)throw new Error(`No coincide la integridad de ${a.name}. No se generó una copia incompleta.`);zip.file(a.path,bytes);manifest.push({path:a.path,hash:a.hash,size:a.size,name:a.name});}zip.file('manifest.json',JSON.stringify(manifest,null,2));zip.file('LEEME.txt','Copia del estado y archivos originales, sin pérdida de calidad. Conservar en un lugar privado. Seleccionar este ZIP en Ajustes → Copias e historial; se verifican los datos y archivos antes de restaurar como una nueva versión.');download(await zip.generateAsync({type:'blob',compression:'STORE'}),'mabell-ramos-copia-completa.zip');}
async function pdf(){const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const doc=new jsPDF();doc.setTextColor(67,38,83);doc.setFont('helvetica','bold');doc.setFontSize(20);doc.text('Mabell Ramos',15,20);doc.setFont('helvetica','normal');doc.setFontSize(10);return {doc,autoTable};}
export async function exportOrderPdf(state:AppState,o:Order){const {doc,autoTable}=await pdf();doc.text(`${o.modality} | ${o.code} | ${o.status}`,15,29);autoTable(doc,{startY:35,theme:'grid',headStyles:{fillColor:[232,221,242],textColor:[67,38,83]},head:[['Contenido','Cantidad / unidad','Precio acordado','Atributos']],body:o.lines.map(l=>[l.name,`${l.quantity} ${l.unit} (tarifa por ${l.baseQuantity})`,money(l.unitPrice),[l.attributes,l.notes].filter(Boolean).join('\n')]),styles:{fontSize:9,overflow:'linebreak'}});let y=(doc as unknown as {lastAutoTable:{finalY:number}}).lastAutoTable.finalY+10;const text=[`Cliente: ${state.clients.find(c=>c.id===o.clientId)?.name||o.contactName||'Venta sin identificar'}`,`Fecha: ${dateLabel(o.deliveryDate)} ${o.deliveryTime} | ${o.location}`,`Total acordado: ${money(o.total)} | Saldo a la fecha: ${money(orderBalance(state,o))}`,`Pago: ${o.paymentTerms||'Por confirmar'}`,`Cambios: ${o.changesTerms||'Por confirmar'}`,`Aceptación: ${o.acceptedAt?dateLabel(o.acceptedAt)+' · '+o.acceptedChannel:'Por confirmar'}`,...o.scope.map(x=>`${x.name}: ${x.status}. ${x.detail} ${x.amount===null?'':money(x.amount)}`)];for(const t of text){const lines=doc.splitTextToSize(t,180);if(y+lines.length*5>278){doc.addPage();y=20;}doc.text(lines,15,y);y+=lines.length*5+3;}doc.save(`${o.code}.pdf`);}
export async function copyOrderText(state:AppState,o:Order){const text=[`Mabell Ramos · ${o.code}`,`${o.modality} para ${state.clients.find(c=>c.id===o.clientId)?.name||o.contactName||'venta presencial'}`,...o.lines.map(l=>`${l.quantity} ${l.unit} · ${l.name}\n${l.attributes}`),`Fecha: ${dateLabel(o.deliveryDate)} ${o.deliveryTime}`,`Total: ${money(o.total)}`,`Pago: ${o.paymentTerms}`,`Cambios: ${o.changesTerms}`,...o.scope.map(x=>`${x.name}: ${x.status} · ${x.detail}`)].join('\n');await navigator.clipboard.writeText(text);}
export async function exportSummaryPdf(state:AppState,from:string,to:string){const {doc,autoTable}=await pdf();doc.text(`Resumen al ${dateLabel(to)} | desde ${dateLabel(from)}`,15,30);const s=financialSummary(state,from,to);autoTable(doc,{startY:40,head:[['Concepto','Valor']],body:[['Ventas entregadas',money(s.sales)],['Cobros',money(s.receipts)],['Devoluciones a clientes',money(s.refunds)],['Pagos',money(s.payments)],['Dinero neto operativo',money(s.net)],['Por cobrar al corte',money(s.receivable)],['Por pagar al corte',money(s.payable)],['Saldo a favor de clientes',money(s.credit)],['Margen estimado en costos revisados',money(s.estimated)],['Cobertura de costos',`${s.reviewedCount} de ${s.deliveredCount} entregas`]],headStyles:{fillColor:[232,221,242],textColor:[67,38,83]},styles:{fontSize:11}});doc.setFontSize(9);doc.text(['Ventas y cobros se muestran por separado. Aportes, préstamos y retiros no son ventas.', 'El margen usa costos revisados, incluido trabajo valorado; no equivale a utilidad contable.', `Estado revisión ${state.revision}. Generado ${dateLabel(iso())}.`],15,210);doc.save(`mabell-ramos-resumen-${from}-${to}.pdf`);}
