import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {openDB} from 'idb';
import type {AppState,Command,EditableCollection,Base,Person,Mode,RepositoryConfig,SessionIdentity,Attachment} from '../domain/types';
import {applyCommand,validateState,DomainError} from '../domain/engine';
import {createDemoState,createEmptyState} from '../domain/seed';
import {base,id,iso} from '../domain/helpers';
import {GitHubRepository} from './github';
import {setAttachmentReader} from './export';
const database=()=>openDB('mabell-ramos-example',1,{upgrade(db){db.createObjectStore('demo');db.createObjectStore('attachments');}});
type Status='Conectado · sin registros guardados'|'Sin conectar'|'Ejemplo en este dispositivo'|'Guardando…'|'Guardado en GitHub'|'Revisar conexión';
interface Context {textSize:'normal'|'large';setTextSize:(size:'normal'|'large')=>void;state:AppState;actor:string;profile:Person;mode:Mode;active:boolean;busy:boolean;status:Status;message:string;needsRefresh:boolean;repository:GitHubRepository|null;identity:SessionIdentity|null;run:(c:Command)=>Promise<void>;save:<T extends Base>(collection:EditableCollection,record:T,reason?:string)=>Promise<void>;notify:(message:string)=>void;startDemo:()=>Promise<void>;resetDemo:()=>Promise<void>;connect:(config:RepositoryConfig,token:string,view:Person)=>Promise<void>;refresh:()=>Promise<void>;logout:()=>void;setProfile:(p:Person)=>void;upload:(file:File,entityType:string,entityId:string)=>Promise<void>;stageAttachment:(file:File,entityType:string,entityId:string)=>Promise<{path:string;sha:string;hash:string}>;readAttachment:(path:string)=>Promise<Blob>;}
const AppContext=createContext<Context|null>(null);
export const useApp=()=>{const c=useContext(AppContext);if(!c)throw new Error('Falta el contexto de la aplicación');return c;};export const useCRM=useApp;
export function AppProvider({children}:{children:ReactNode}){
 const [textSize,setTextSizeState]=useState<'normal'|'large'>(()=>localStorage.getItem('mr:text-size')==='large'?'large':'normal');
 const setTextSize=(size:'normal'|'large')=>{setTextSizeState(size);localStorage.setItem('mr:text-size',size);};
 useEffect(()=>{document.documentElement.dataset.textSize=textSize;},[textSize]);
 const [state,setState]=useState(createEmptyState),[profile,setProfileState]=useState<Person>(()=>localStorage.getItem('mr:profile')==='Mabel'?'Mabel':'Ana'),[mode,setMode]=useState<Mode>('demo'),[active,setActive]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState<Status>('Sin conectar'),[message,setMessage]=useState(''),[needsRefresh,setNeedsRefresh]=useState(false),[repository,setRepository]=useState<GitHubRepository|null>(null),[identity,setIdentity]=useState<SessionIdentity|null>(null);
 const current=useRef(state),repoRef=useRef<GitHubRepository|null>(null),sha=useRef<string|null>(null),lock=useRef(false);current.current=state;repoRef.current=repository;
 const setProfile=(p:Person)=>{setProfileState(p);localStorage.setItem('mr:profile',p);};
 const actor=mode==='github'&&identity?`${identity.login}${state.settings.profiles.find(p=>p.githubLogin.toLowerCase()===identity.login.toLowerCase())?.name?' · '+state.settings.profiles.find(p=>p.githubLogin.toLowerCase()===identity.login.toLowerCase())!.name:''}`:`${profile} · demostración`;
 const notify=(text:string)=>setMessage(text);
 const readAttachment=async(path:string)=>{if(repoRef.current)return repoRef.current.readAttachment(path);const db=await database(),blob=await db.get('attachments',path) as Blob|undefined;if(!blob)throw new Error('El archivo de ejemplo no está en este dispositivo');return blob;};
 useEffect(()=>{setAttachmentReader(readAttachment);return()=>setAttachmentReader(null);},[repository]);
 const startDemo=async()=>{repoRef.current?.disconnect();const db=await database();let demo=await db.get('demo','state') as AppState|undefined;if(!demo){demo=createDemoState();await db.put('demo',demo,'state');}setState(validateState(demo));setRepository(null);setIdentity(null);setMode('demo');setActive(true);setStatus('Ejemplo en este dispositivo');setNeedsRefresh(false);setMessage('Estás practicando con datos ficticios. No se guardan en GitHub.');};
 const resetDemo=async()=>{const demo=createDemoState();const db=await database();await db.put('demo',demo,'state');setState(demo);setNeedsRefresh(false);notify('Ejemplo reiniciado; los datos reales no se han tocado.');};
 const connect=async(config:RepositoryConfig,token:string,view:Person)=>{if(lock.current)throw new Error('Espera a que termine la operación');lock.current=true;setBusy(true);let next:GitHubRepository|null=null;try{next=new GitHubRepository(config,token);const who=await next.connect(),loaded=await next.load();let data=loaded.state;if(!data){data=createEmptyState();data.settings.profiles=data.settings.profiles.map(p=>p.name===view?{...p,githubLogin:who.login}:p);}sha.current=loaded.sha;setState(data);setRepository(next);setIdentity(who);setProfile(view);setMode('github');setActive(true);setNeedsRefresh(false);setStatus(loaded.state?'Guardado en GitHub':'Conectado · sin registros guardados');localStorage.setItem('mr:repository',JSON.stringify(config));setMessage(loaded.state?'Datos privados cargados desde GitHub.':'Conexión verificada. El primer cambio creará el archivo privado, sin datos de demostración.');}catch(e){next?.disconnect();throw e;}finally{lock.current=false;setBusy(false);}};
 const refresh=async()=>{if(lock.current)return;lock.current=true;setBusy(true);try{if(repository){const loaded=await repository.load();if(!loaded.state){if(sha.current)throw new Error('El archivo compartido fue eliminado; no se reemplazará automáticamente.');}else setState(loaded.state);sha.current=loaded.sha;setStatus(loaded.state?'Guardado en GitHub':'Conectado · sin registros guardados');}else {const db=await database();const saved=await db.get('demo','state');if(saved)setState(validateState(saved));}setNeedsRefresh(false);setMessage('Datos actualizados. Revisa tu formulario antes de guardar.');}catch(e){setNeedsRefresh(true);setStatus('Revisar conexión');setMessage((e as Error).message);throw e;}finally{lock.current=false;setBusy(false);}};
 const run=async(command:Command)=>{if(!active)throw new Error('Abre el ejemplo o conecta el repositorio');if(lock.current)throw new Error('Espera a que termine el guardado');if(needsRefresh)throw new Error('Actualiza los datos y comprueba si la operación ya existe antes de repetirla');lock.current=true;setBusy(true);setStatus('Guardando…');const before=current.current;try{const next=applyCommand(before,{id:id(),actor,at:iso(),expectedStateRevision:before.revision,command});if(repository){const saved=await repository.save(next,sha.current,`${actor}: ${command.type} · revisión ${next.revision}`);sha.current=saved.sha;setStatus('Guardado en GitHub');}else {const db=await database(),tx=db.transaction('demo','readwrite');const saved=await tx.store.get('state') as AppState|undefined;if(saved&&saved.revision!==before.revision){tx.abort();throw new Error('El ejemplo cambió en otra pestaña. Actualiza los datos.');}await tx.store.put(next,'state');await tx.done;setStatus('Ejemplo en este dispositivo');}current.current=next;setState(next);setMessage(repository?'Guardado en el repositorio privado.':'Guardado en el ejemplo de este dispositivo.');}catch(e){if(repository&&!(e instanceof DomainError)){setNeedsRefresh(true);setStatus('Revisar conexión');}else if(repository)setStatus(sha.current?'Guardado en GitHub':'Conectado · sin registros guardados');else setStatus('Ejemplo en este dispositivo');setMessage((e as Error).message);throw e;}finally{lock.current=false;setBusy(false);}};
 const save=async<T extends Base>(collection:EditableCollection,record:T,reason?:string)=>run({type:'save',collection,record:record as Base&Record<string,unknown>,expectedRevision:record.revision,reason});
 const logout=()=>{repository?.disconnect();setRepository(null);setIdentity(null);setActive(false);setState(createEmptyState());setStatus('Sin conectar');setMessage('Sesión cerrada');sha.current=null;setNeedsRefresh(false);for(const key of Object.keys(sessionStorage))if(key.startsWith('mr:form:'))sessionStorage.removeItem(key);};
 const stageAttachment=async(file:File,entityType:string,entityId:string)=>{if(file.size>8*1024*1024)throw new Error('Adjunta un archivo de hasta 8 MiB; se conserva sin reducir calidad.');if(!['application/pdf','image/png','image/jpeg','image/webp','text/plain','text/csv'].includes(file.type))throw new Error('Usa PDF, imagen, texto o CSV');let info:{path:string;sha:string;hash:string};if(repository)info=await repository.writeAttachment(file,entityType,entityId);else {const path=`demo/${id()}/${file.name}`;const bytes=await file.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');const db=await database();await db.put('attachments',file,path);info={path,sha:'demo',hash};}return info;};
 const upload=async(file:File,entityType:string,entityId:string)=>{const info=await stageAttachment(file,entityType,entityId);const record:Attachment={...base(),name:file.name,mime:file.type,size:file.size,...info,entityType,entityId,uploadedBy:actor};await save('attachments',record);};
 useEffect(()=>{if(!active||mode!=='github')return;const onFocus=()=>{if(!lock.current&&!needsRefresh)void refresh().catch(()=>{});};window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus);},[active,mode,repository,needsRefresh]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),12000);return()=>clearTimeout(t);},[message]);
 return <AppContext.Provider value={{textSize,setTextSize,state,actor,profile,mode,active,busy,status,message,needsRefresh,repository,identity,run,save,notify,startDemo,resetDemo,connect,refresh,logout,setProfile,upload,stageAttachment,readAttachment}}>{children}</AppContext.Provider>;
}
