import {useMemo, useState, type FormEvent} from 'react';
import {Link, useNavigate, useParams} from 'react-router-dom';
import {useCRM} from '../services/store';
import {base, cents, dateLabel, decimal, id, iso, money, needs, normalize, people, today} from '../domain/helpers';
import {orderTotal, orderBalance} from '../domain/selectors';
import type {AppState, Base, Fair, FairLine, MoneyRecord, Order, OrderLine, Person, Task} from '../domain/types';
import {blankOrder, lineFromReference, MoneyInput, useFormDraft} from './Orders';
import {Actions, Badge, Button, Card, Empty, ErrorBox, Field, Input, Modal, Notice, PageHeader, Select, Textarea} from '../components/ui';

const errorText=(e:unknown)=>e instanceof Error?e.message:'No se pudo guardar. El formulario conserva lo que escribiste.';
const localTime=(value:string)=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value)).replace(' ','T');
const instant=(value:string)=>new Date(value+':00-05:00').toISOString();
const newFair=(profile:Person):Fair=>({...base(),name:'',date:today(),location:'',responsible:profile,type:'Feria',mode:'Individual',lines:[],closed:false,notes:''});
const activeOrders=(state:AppState,fair:Fair)=>state.orders.filter(o=>o.eventId===fair.id&&!o.isSimulation&&!o.archived);
const fairSales=(state:AppState,fair:Fair)=>state.sales.filter(s=>s.eventId===fair.id&&state.orders.some(o=>o.id===s.orderId&&!o.isSimulation&&!o.archived));
const salesAmount=(state:AppState,fair:Fair,modality?:Order['modality'])=>fairSales(state,fair).filter(s=>!modality||s.modality===modality).reduce((n,s)=>n+s.amount+s.adjustments.reduce((a,x)=>a+x.amount,0),0);
const receivedAmount=(state:AppState,fair:Fair)=>{const ids=new Set(activeOrders(state,fair).map(o=>o.id));return state.money.filter(m=>m.kind==='Cobro'||m.kind==='Devolución al cliente').reduce((n,m)=>n+(m.kind==='Cobro'?1:-1)*m.allocations.filter(a=>ids.has(a.entityId)).reduce((a,x)=>a+x.amount,0),0);};
function productSold(state:AppState,fair:Fair,line:FairLine):number|null {
  if(fair.mode==='Resumen')return null;
  const lines=activeOrders(state,fair).filter(o=>o.status==='Entregado'&&o.modality==='Productos').flatMap(o=>o.lines).filter(l=>l.referenceType==='product'&&l.referenceId===line.productId);
  if(lines.some(l=>normalize(l.unit)!==normalize(line.unit)))return null;
  return lines.reduce((n,l)=>n+l.quantity,0);
}
const downloadCsv=(name:string,rows:(string|number|null)[][])=>{const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v??'Por registrar').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

export function FairsScreen() {
  const {state,profile,save,busy}=useCRM();const navigate=useNavigate();const [search,setSearch]=useState(''),[filter,setFilter]=useState('Todas'),[open,setOpen]=useState(false),[error,setError]=useState('');
  const initial=useMemo(()=>newFair(profile),[profile]);const {draft,setDraft,clear,reset}=useFormDraft('fair-new',initial);
  const fairs=state.fairs.filter(f=>!f.archived&&normalize(f.name+' '+f.location).includes(normalize(search))&&(filter==='Todas'||f.closed===(filter==='Cerradas'))).sort((a,b)=>b.date.localeCompare(a.date));
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{if(!draft.name.trim()||!draft.date||!draft.location.trim())throw new Error('Indica el nombre, la fecha y el lugar de la jornada.');await save('fairs',draft);clear();setOpen(false);navigate('/ferias/'+draft.id);}catch(e){setError(errorText(e));}};
  return <><PageHeader eyebrow="Atención presencial" title="Ferias y jornadas" description="Registra ventas directas, productos llevados y gastos compartidos. El catering conserva su propio acuerdo." actions={<><Link className="btn btn-secondary" to="/pedidos">Volver a Pedidos</Link><Button onClick={()=>{setOpen(true);setError('');}}>Nueva jornada</Button></>}/><Card><div className="form-grid"><Field label="Buscar una jornada"><Input value={search} onChange={e=>setSearch(e.target.value)}/></Field><Field label="Estado"><Select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todas</option><option>Abiertas</option><option>Cerradas</option></Select></Field></div></Card><div className="card-list">{fairs.map(f=><Card key={f.id}><div className="list-row"><div className="list-main"><Link className="text-link" to={'/ferias/'+f.id}>{f.name}</Link><p>{dateLabel(f.date)} · {f.location} · {f.responsible}</p><small>{f.type} · {f.mode==='Individual'?'Ventas individuales':'Resumen histórico, sin detalle por producto'}</small></div><div className="stack"><Badge tone={f.closed?'success':'purple'}>{f.closed?'Cerrada':'Abierta'}</Badge><strong>{money(salesAmount(state,f))} vendidos</strong><small>{money(receivedAmount(state,f))} de cobros netos</small></div></div></Card>)}</div>{!fairs.length&&<Empty title="No hay jornadas con este filtro" text="Crea una jornada cuando necesites registrar una feria o vincular actividades del mismo evento."/>}<Modal open={open} onClose={()=>setOpen(false)} title="Nueva jornada"><form onSubmit={submit}><ErrorBox error={error}/><FairFields fair={draft} onChange={setDraft}/><Notice>Si conoces cada venta, usa ventas individuales. El resumen se reserva para una jornada histórica cuyo único respaldo son los totales; ambos métodos no se suman en la misma jornada.</Notice><Actions><Button disabled={busy}>Crear jornada</Button><Button type="button" variant="ghost" onClick={reset}>Descartar borrador</Button></Actions></form></Modal></>;
}

function FairFields({fair,onChange,modeLocked=false}:{fair:Fair;onChange:(f:Fair)=>void;modeLocked?:boolean}) {
  const patch=(p:Partial<Fair>)=>onChange({...fair,...p});
  return <div className="form-grid"><div className="span-2"><Field label="Nombre"><Input required data-modal-first value={fair.name} onChange={e=>patch({name:e.target.value})}/></Field></div><Field label="Fecha de la jornada"><Input required type="date" value={fair.date} onChange={e=>patch({date:e.target.value})}/></Field><Field label="Responsable"><Select value={fair.responsible} onChange={e=>patch({responsible:e.target.value as Person})}>{people.map(p=><option key={p}>{p}</option>)}</Select></Field><div className="span-2"><Field label="Lugar"><Input required value={fair.location} onChange={e=>patch({location:e.target.value})}/></Field></div><Field label="Actividad"><Select value={fair.type} onChange={e=>patch({type:e.target.value as Fair['type']})}><option>Feria</option><option>Reunión/evento</option></Select></Field><Field label="Cómo registrar las ventas" hint={modeLocked?'Con ventas registradas, el método se conserva para evitar duplicados.':undefined}><Select disabled={modeLocked} value={fair.mode} onChange={e=>patch({mode:e.target.value as Fair['mode']})}><option value="Individual">Cada venta por separado</option><option value="Resumen">Sólo un total histórico de la jornada</option></Select></Field><div className="span-2"><Field label="Notas y apoyo de la jornada"><Textarea value={fair.notes} onChange={e=>patch({notes:e.target.value})}/></Field></div></div>;
}

export function FairDetailScreen() {
  const {id:fairId}=useParams();const {state,profile,save,busy,notify}=useCRM();const fair=state.fairs.find(f=>f.id===fairId);
  const [modal,setModal]=useState<'sale'|'edit'|'stock'|'close'|'task'|null>(null),[draftFair,setDraftFair]=useState<Fair|null>(null),[task,setTask]=useState<Task|null>(null),[error,setError]=useState(''),[checked,setChecked]=useState(false),[reason,setReason]=useState(''),[productId,setProductId]=useState('');
  if(!fair)return <Empty title="Jornada no encontrada" action={<Link to="/ferias">Volver a Ferias</Link>}/>;
  const orders=activeOrders(state,fair),tasks=state.tasks.filter(t=>t.eventId===fair.id&&!t.archived),purchases=state.purchases.filter(p=>p.eventId===fair.id&&!p.archived);
  const unattributed=orders.filter(o=>o.status==='Entregado'&&o.modality==='Productos').flatMap(o=>o.lines).filter(l=>l.referenceType!=='product'||!fair.lines.some(f=>f.productId===l.referenceId&&normalize(f.unit)===normalize(l.unit)));
  const open=(kind:typeof modal)=>{setModal(kind);setError('');setChecked(false);setReason('');setDraftFair(structuredClone(fair));if(kind==='task')setTask({...base(),title:'',date:fair.date,time:'',minutes:null,responsible:profile,collaborator:'',orderId:null,clientId:null,eventId:fair.id,kind:'Preparación',status:'Pendiente',resource:'',resourceStatus:'No aplica',purpose:'Atender solicitud/pedido',notes:'',result:''});};
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{
    if((modal==='stock'||modal==='edit')&&draftFair){if(modal==='stock'&&!checked)throw new Error('Confirma que revisaste las cantidades; cero sólo significa ninguna unidad si lo comprobaste.');if(!draftFair.name.trim()||!draftFair.date||!draftFair.location.trim())throw new Error('Indica nombre, fecha y lugar.');for(const l of draftFair.lines)if([l.brought,l.returned,l.samples,l.waste].some(n=>!Number.isInteger(n)||n<0))throw new Error('Las cantidades deben ser enteras y no negativas.');await save('fairs',draftFair,modal==='stock'?'Revisión de cantidades de la jornada':'Actualización de jornada');}
    if(modal==='close'){if(!checked)throw new Error('Revisa los registros antes de cerrar.');if(!reason.trim())throw new Error('Deja constancia de la revisión y explica las diferencias que queden pendientes.');await save('fairs',{...fair,closed:!fair.closed,notes:[fair.notes,`${fair.closed?'Reapertura':'Cierre'}: ${reason}`].filter(Boolean).join('\n')},reason);}
    if(modal==='task'&&task){if(!task.title.trim()||!task.date)throw new Error('Indica qué hay que hacer y para cuándo.');await save('tasks',task);}
    setModal(null);notify('Jornada actualizada.');
  }catch(e){setError(errorText(e));}};
  const exportCsv=()=>{downloadCsv(`jornada-${fair.date}-${fair.id.slice(0,6)}.csv`,[['Jornada',fair.name,'Fecha',fair.date,'Método',fair.mode,'Generado',iso()],['Ventas productos (S/)',decimal(salesAmount(state,fair,'Productos')),'Ventas catering (S/)',decimal(salesAmount(state,fair,'Catering')),'Cobros netos (S/)',decimal(receivedAmount(state,fair))],[],['Producto','Unidad','Llevado','Vendido registrado','Retornado','Degustación','Merma','Diferencia'],...fair.lines.map(l=>{const sold=productSold(state,fair,l);return[l.name,l.unit,l.brought,sold,l.returned,l.samples,l.waste,sold===null?null:l.brought-sold-l.returned-l.samples-l.waste];}),[],['Pedido','Modalidad','Estado','Cliente','Fecha entrega','Venta acordada S/','Pendiente S/'],...orders.map(o=>[o.code,o.modality,o.status,state.clients.find(c=>c.id===o.clientId)?.name||o.contactName||'Venta sin cliente identificado',o.deliveredAt||o.deliveryDate,decimal(o.total),decimal(orderBalance(state,o))])]);notify('Informe descargado; incluye fecha de generación y datos registrados.');};
  return <><PageHeader eyebrow={fair.type} title={fair.name} description={`${dateLabel(fair.date)} · ${fair.location} · ${fair.responsible}`} actions={<><Link className="btn btn-secondary" to="/ferias">Volver</Link><Button variant="secondary" onClick={exportCsv}>Descargar resumen</Button>{!fair.closed&&<Button variant="ghost" onClick={()=>open('edit')}>Editar jornada</Button>}</>}/><ErrorBox error={!modal?error:''}/><div className="toolbar"><Badge tone={fair.closed?'success':'purple'}>{fair.closed?'Jornada cerrada':'Jornada abierta'}</Badge><Badge>{fair.mode==='Individual'?'Ventas individuales':'Resumen histórico'}</Badge>{!fair.closed&&<Button onClick={()=>open('sale')} disabled={fair.mode==='Resumen'&&orders.some(o=>o.modality==='Productos'&&o.status!=='Cancelado')}>{fair.mode==='Resumen'?'Registrar total histórico':'Venta rápida'}</Button>}<Link className="btn btn-secondary" to={`/pedidos/nuevo?modality=Catering&event=${fair.id}`}>Acuerdo de catering vinculado</Link><Link className="btn btn-secondary" to={`/dinero?event=${fair.id}&action=compra`}>Compra o gasto de la jornada</Link><Button variant="ghost" onClick={()=>open('close')}>{fair.closed?'Reabrir con motivo':'Revisar y cerrar'}</Button></div>
  <div className="split-grid"><Card title="Ventas entregadas"><p><strong>{money(salesAmount(state,fair,'Productos'))}</strong> · productos</p><p><strong>{money(salesAmount(state,fair,'Catering'))}</strong> · catering</p><p className="muted">Importes comerciales después de ajustes. No son dinero recibido ni utilidad.</p></Card><Card title="Dinero recibido"><p><strong>{money(receivedAmount(state,fair))}</strong> · cobros menos devoluciones</p><Link className="text-link" to={`/dinero?event=${fair.id}`}>Ver cobros, compras y pagos</Link><p className="muted">Un gasto común se registra una sola vez y se vincula a esta jornada.</p></Card></div>
  <Card title="Productos de la jornada" subtitle="Control en la misma unidad de venta; no constituye un inventario completo." action={!fair.closed&&<Button variant="secondary" onClick={()=>open('stock')}>Registrar cantidades</Button>}>{fair.mode==='Resumen'&&<Notice>Con sólo un total histórico no se puede deducir cuántos productos se vendieron. Las cantidades de venta permanecen por verificar.</Notice>}{fair.lines.length?<div className="table-wrap"><table className="table"><thead><tr><th>Producto / unidad</th><th>Llevado</th><th>Vendido</th><th>Retornado</th><th>Degustación</th><th>Merma</th><th>Diferencia</th></tr></thead><tbody>{fair.lines.map(l=>{const sold=productSold(state,fair,l),difference=sold===null?null:l.brought-sold-l.returned-l.samples-l.waste;return <tr key={l.productId}><td>{l.name}<small className="muted"> · {l.unit}</small></td><td>{l.brought}</td><td>{sold??'Por revisar'}</td><td>{l.returned}</td><td>{l.samples}</td><td>{l.waste}</td><td>{difference===null?'Por revisar':difference===0?'Cuadra':`${difference} por revisar`}</td></tr>;})}</tbody></table></div>:<Empty text="Registra lo llevado y revisa retornos, degustaciones y merma al cerrar; los ceros requieren revisión, no se presumen."/>}{unattributed.length>0&&<Notice tone="warning">{unattributed.length} línea(s) vendida(s) no se comparan con lo llevado: usan otra presentación, un paquete o una descripción específica. Revisa sus unidades antes de interpretar la diferencia.</Notice>}</Card>
  <Card title="Ventas y acuerdos vinculados">{orders.length?orders.map(o=><div className="list-row" key={o.id}><div className="list-main"><Link className="text-link" to={'/pedidos/'+o.id}>{o.code}</Link><p>{state.clients.find(c=>c.id===o.clientId)?.name||o.contactName||'Venta sin cliente identificado'} · {o.modality}</p><small>{o.lines.map(l=>`${l.quantity} ${l.unit}: ${l.name}`).join(' · ')}</small></div><div><Badge>{o.status}</Badge><p>{money(o.total)} · pendiente {money(orderBalance(state,o))}</p></div></div>):<Empty text="La jornada no tiene ventas o acuerdos registrados todavía."/>}</Card>
  <div className="split-grid"><Card title="Preparación y tareas" action={<Button variant="secondary" onClick={()=>open('task')}>Añadir tarea</Button>}>{tasks.length?tasks.map(t=><div className="list-row" key={t.id}><div className="list-main"><strong>{t.title}</strong><p>{dateLabel(t.date)} {t.time} · {t.responsible}</p></div><Select aria-label={'Estado de '+t.title} value={t.status} disabled={busy} onChange={e=>void save('tasks',{...t,status:e.target.value as Task['status']}).catch(e=>setError(errorText(e)))}>{['Pendiente','En curso','Completada','Cancelada'].map(s=><option key={s}>{s}</option>)}</Select></div>):<Empty text="Programa producción, compras, traslado, montaje y retorno según esta jornada."/>}</Card><Card title="Compras vinculadas" action={<Link className="text-link" to={`/dinero?event=${fair.id}`}>Revisar en Dinero</Link>}>{purchases.length?purchases.map(p=><div className="list-row" key={p.id}><div><strong>{p.description}</strong><p>{dateLabel(p.date)} · {p.status}</p><small>{p.allocations.length?'Tiene reparto documentado':'Sin reparto a pedidos individuales'}</small></div><span>{money(p.businessAmount+p.adjustments.reduce((n,a)=>n+a.amount,0))}</span></div>):<Empty text="Vincula cada compra a la jornada una sola vez; comprar y pagar son registros distintos."/>}</Card></div>{fair.notes&&<Card title="Notas de la jornada"><p style={{whiteSpace:'pre-wrap'}}>{fair.notes}</p></Card>}
  <Modal open={modal==='sale'} onClose={()=>setModal(null)} title={fair.mode==='Resumen'?'Resumen histórico de ventas':'Venta rápida en feria'} wide><FairSaleForm key={fair.id} fair={fair} onDone={()=>setModal(null)}/></Modal>
  <Modal open={!!modal&&modal!=='sale'} onClose={()=>setModal(null)} title={modal==='stock'?'Cantidades llevadas y retornadas':modal==='edit'?'Editar jornada':modal==='task'?'Programar tarea':fair.closed?'Reabrir la jornada':'Revisar el cierre'} wide={modal==='stock'}><form onSubmit={submit}><ErrorBox error={error}/>{modal==='edit'&&draftFair&&<FairFields fair={draftFair} onChange={setDraftFair} modeLocked={orders.some(o=>o.modality==='Productos')}/>}
  {modal==='stock'&&draftFair&&<><div className="toolbar"><Field label="Producto"><Select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Selecciona producto</option>{state.products.filter(p=>!p.archived&&!draftFair.lines.some(l=>l.productId===p.id)).map(p=><option value={p.id} key={p.id}>{p.name} · {p.unit}</option>)}</Select></Field><Button type="button" variant="secondary" disabled={!productId} onClick={()=>{const p=state.products.find(x=>x.id===productId);if(p)setDraftFair({...draftFair,lines:[...draftFair.lines,{productId:p.id,name:p.name,unit:p.unit,brought:0,returned:0,samples:0,waste:0}]});setProductId('');}}>Añadir</Button></div>{draftFair.lines.map((l,i)=><Card key={l.productId} title={`${l.name} · ${l.unit}`} action={<Button type="button" variant="ghost" onClick={()=>setDraftFair({...draftFair,lines:draftFair.lines.filter((_,j)=>i!==j)})}>Quitar control</Button>}><div className="form-grid">{(['brought','returned','samples','waste'] as const).map(k=><Field key={k} label={{brought:'Llevado',returned:'Retornado',samples:'Degustación',waste:'Merma'}[k]}><Input type="number" required min="0" step="1" value={l[k]} onChange={e=>setDraftFair({...draftFair,lines:draftFair.lines.map((x,j)=>j===i?{...x,[k]:Number(e.target.value)}:x)})}/></Field>)}</div></Card>)}<Notice>Usa siempre la unidad indicada. Revisa y sustituye los ceros que todavía no correspondan a una cantidad comprobada.</Notice><label className="row"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Revisé todas estas cantidades en la unidad indicada; los ceros corresponden a ninguna unidad comprobada.</label></>}
  {modal==='close'&&<><Notice>{fair.closed?'La reapertura permite corregir y añadir datos, conservando el historial.':'Revisa ventas, cobros, compras y cantidades; una diferencia puede permanecer pendiente si dejas la explicación. Cerrar no añade ni borra dinero.'}</Notice><Field label="Constancia de revisión / motivo"><Textarea required value={reason} onChange={e=>setReason(e.target.value)}/></Field><label className="row"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>{fair.closed?'Confirmo que necesito reabrir para revisar los registros.':'Revisé las cantidades, los cobros y los registros sin duplicar ventas ni gastos.'}</label></>}
  {modal==='task'&&task&&<div className="form-grid"><div className="span-2"><Field label="Qué hacer"><Input required value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/></Field></div><Field label="Fecha"><Input required type="date" value={task.date} onChange={e=>setTask({...task,date:e.target.value})}/></Field><Field label="Hora"><Input type="time" value={task.time} onChange={e=>setTask({...task,time:e.target.value})}/></Field><Field label="Etapa"><Select value={task.kind} onChange={e=>setTask({...task,kind:e.target.value as Task['kind']})}>{['Atención','Compra','Preparación','Empaque','Entrega','Montaje','Seguimiento','Otra'].map(k=><option key={k}>{k}</option>)}</Select></Field><Field label="Responsable"><Select value={task.responsible} onChange={e=>setTask({...task,responsible:e.target.value as Person})}>{people.map(p=><option key={p}>{p}</option>)}</Select></Field><Field label="Duración estimada (min)"><Input type="number" min="1" value={task.minutes??''} onChange={e=>setTask({...task,minutes:e.target.value?Number(e.target.value):null})}/></Field><Field label="Apoyo / recurso"><Input value={task.resource} onChange={e=>setTask({...task,resource:e.target.value})}/></Field><Field label="Disponibilidad"><Select value={task.resourceStatus} onChange={e=>setTask({...task,resourceStatus:e.target.value as Task['resourceStatus']})}><option>No aplica</option><option>Por confirmar</option><option>Confirmado</option></Select></Field><Field label="Notas"><Textarea value={task.notes} onChange={e=>setTask({...task,notes:e.target.value})}/></Field></div>}
  <Actions><Button disabled={busy||((modal==='close'||modal==='stock')&&!checked)}>Guardar</Button><Button type="button" variant="secondary" onClick={()=>setModal(null)}>Volver</Button></Actions></form></Modal></>;
}

interface SaleDraft extends Base {order:Order;received:string;method:string;accountId:string;cashDate:string;accepted:string;reference:string;reviewed:boolean;moneyId:string}

function FairSaleForm({fair,onDone}:{fair:Fair;onDone:()=>void}) {
  const {state,profile,run,busy,notify}=useCRM();
  const initial=useMemo<SaleDraft>(()=>{const order={...blankOrder(profile),eventId:fair.id,location:fair.location,deliveryDate:fair.date,deliveryMode:'Retiro' as const,transport:0,paymentTerms:'Venta presencial; cobro y saldo registrados por separado.',changesTerms:'El contenido y el precio se confirman al entregar; cualquier cambio posterior se registra como ajuste.',internalNotes:fair.mode==='Resumen'?'Resumen histórico de jornada; no sumar a ventas individuales.':''};if(fair.mode==='Resumen')order.lines=[{...lineFromReference(state,'custom:'),name:'Resumen histórico de ventas de la jornada',unit:'resumen',quantity:1,baseQuantity:1,unitsPerPack:1}];return {...base(),order,received:'',method:'',accountId:'',cashDate:fair.date,accepted:fair.date===today()?localTime(iso()):'',reference:'',reviewed:false,moneyId:id()};},[fair.id,profile]);
  const {draft,setDraft,clear}=useFormDraft('fair-sale-'+fair.id,initial);const [error,setError]=useState(''),[productId,setProductId]=useState(''),[advanced,setAdvanced]=useState(false),[saving,setSaving]=useState(false);
  const patch=(p:Partial<SaleDraft>)=>setDraft({...draft,...p});const patchOrder=(p:Partial<Order>)=>patch({order:{...draft.order,...p}});const total=orderTotal(draft.order);
  const updateLine=(lineId:string,p:Partial<OrderLine>)=>patchOrder({lines:draft.order.lines.map(l=>l.id===lineId?{...l,...p}:l)});
  const existing=state.orders.find(o=>o.id===draft.order.id);const locked=!!existing&&['Confirmado','En preparación','Entregado'].includes(existing.status);
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setSaving(true);try{
    if(fair.closed)throw new Error('Reabre la jornada antes de añadir ventas.');if(!draft.reviewed)throw new Error('Confirma la entrega, el precio y el cobro real.');if(!draft.order.lines.length||draft.order.lines.some(l=>!l.name.trim()||!Number.isInteger(l.quantity)||l.quantity<=0||l.unitPrice===null||l.unitPrice<0))throw new Error('Completa productos, cantidades y precios de esta venta.');if(!draft.accepted)throw new Error('Indica la fecha y hora reales de aceptación, especialmente si registras una jornada anterior.');
    if(!draft.received.trim())throw new Error('Escribe el dinero realmente recibido; usa 0 sólo si confirmaste que no hubo cobro.');const received=cents(draft.received);if(fair.mode==='Resumen'&&!draft.order.customerNotes.trim())throw new Error('Indica el respaldo conocido del total de ventas y de los cobros.');if(fair.mode==='Resumen'&&received===0&&!draft.order.clientId)throw new Error('Un resumen sin cobros requiere un cliente identificado con saldo pendiente; si sólo desconoces el cobro, no registres cero.');if(received<0||received>total)throw new Error('El importe cobrado debe estar entre cero y el total vendido.');if(received<total&&!draft.order.clientId&&!draft.reference.trim())throw new Error('Para un saldo pendiente, elige un cliente o registra una referencia de contacto que permita cobrar.');if(received>0&&(!draft.method||!draft.cashDate))throw new Error('Indica el medio y la fecha real del dinero recibido.');
    if(fair.mode==='Resumen'&&state.orders.some(o=>o.eventId===fair.id&&o.id!==draft.order.id&&o.modality==='Productos'&&o.status!=='Cancelado'))throw new Error('Esta jornada ya contiene ventas de productos. No se añadirá un resumen que las duplique.');
    const o:Order={...draft.order,total,contactName:draft.order.clientId?state.clients.find(c=>c.id===draft.order.clientId)?.name||draft.order.contactName:draft.order.contactName,internalNotes:[draft.order.internalNotes,received<total?`Referencia para cobrar: ${draft.reference}`:''].filter(Boolean).join('\n'),lines:draft.order.lines.map(l=>({...l,priceKind:'Aprobado'}))};
    // The atomic command and stable IDs protect a retry after uncertain connectivity.
    if(existing){if(existing.status==='Entregado'&&(received===0||state.money.some(m=>m.id===draft.moneyId))){clear();notify('Este registro ya estaba guardado; no se duplicó.');onDone();return;}throw new Error('Este código ya existe. Revisa el registro antes de repetir la venta.');}
    const record:MoneyRecord|null=received>0?{...base(),id:draft.moneyId,kind:'Cobro',amount:received,date:draft.cashDate,accountId:draft.accountId||null,toAccountId:null,method:draft.method,reference:`Venta ${o.code} · ${fair.name}`,notes:'Dinero recibido en la jornada; no equivale automáticamente al total vendido.',allocations:[{entityId:o.id,amount:received}],reversalOf:null,reversedBy:null,direction:'Entrada',requestId:draft.moneyId}:null;
    await run({type:'fairSale',order:o,date:o.deliveryDate,acceptedAt:instant(draft.accepted),received:record});
    clear();notify('Venta y cobro guardados. Si quedó pendiente, podrás verlo en Dinero.');onDone();
  }catch(e){setError(errorText(e));}finally{setSaving(false);}};
  return <form onSubmit={submit}><ErrorBox error={error}/>{existing&&<Notice tone="warning">Ya existe un registro de este formulario: <Link to={'/pedidos/'+existing.id}>{existing.code} · {existing.status}</Link>. Si un guardado se interrumpió, reintenta para completar lo pendiente sin crear otra venta.</Notice>}
  {fair.mode==='Resumen'?<><Notice>Usa este total sólo cuando no dispones de ventas individuales. No se deducirán compradores, sabores ni cantidades a partir del importe.</Notice><MoneyInput label="Total de ventas entregadas según el respaldo (S/)" disabled={locked} value={draft.order.lines[0]?.unitPrice??null} onChange={text=>updateLine(draft.order.lines[0].id,{unitPrice:text.trim()?cents(text):null,priceKind:'Aprobado'})}/><Field label="Respaldo o explicación del total"><Textarea required value={draft.order.customerNotes} disabled={locked} onChange={e=>patchOrder({customerNotes:e.target.value})}/></Field></>:<><div className="toolbar"><Field label="Producto y presentación"><Select value={productId} disabled={locked} onChange={e=>setProductId(e.target.value)}><option value="">Selecciona una referencia</option>{state.products.filter(p=>p.status==='Aprobado'&&!p.archived).map(p=><option key={p.id} value={p.id}>{p.name} · {p.unit} · {money(p.price)} / {p.baseQuantity}</option>)}</Select></Field><Button type="button" variant="secondary" disabled={!productId||locked} onClick={()=>{patchOrder({lines:[...draft.order.lines,lineFromReference(state,'product:'+productId)]});setProductId('');}}>Añadir</Button><Button type="button" variant="ghost" disabled={locked} onClick={()=>patchOrder({lines:[...draft.order.lines,lineFromReference(state,'custom:')]})}>Venta específica</Button></div>{draft.order.lines.map(l=><Card key={l.id} title={l.name||'Producto vendido'} action={!locked&&<Button type="button" variant="ghost" onClick={()=>patchOrder({lines:draft.order.lines.filter(x=>x.id!==l.id)})}>Quitar</Button>}><div className="form-grid"><Field label="Nombre / presentación"><Input value={l.name} disabled={locked} onChange={e=>updateLine(l.id,{name:e.target.value})}/></Field><Field label="Cantidad"><Input type="number" min="1" step="1" value={l.quantity||''} disabled={locked} onChange={e=>updateLine(l.id,{quantity:Number(e.target.value)})}/></Field><MoneyInput label={`Precio por ${l.baseQuantity} ${l.unit} (S/)`} disabled={locked} value={l.unitPrice} onChange={text=>{if(!locked)updateLine(l.id,{unitPrice:text.trim()?cents(text):null,priceKind:'Aprobado'});}}/><Field label="Unidad"><Input value={l.unit} disabled={locked} onChange={e=>updateLine(l.id,{unit:e.target.value})}/></Field></div><details><summary>Precisar relleno, tamaño o empaque</summary><Field label="Atributos de esta venta"><Textarea value={l.attributes} disabled={locked} onChange={e=>updateLine(l.id,{attributes:e.target.value})}/></Field></details></Card>)}</>}
  <Card title={`Total vendido: ${money(total)}`}><div className="form-grid"><Field label="Dinero recibido ahora (S/)" hint="0 si no se cobró; el restante quedará pendiente."><Input required inputMode="decimal" value={draft.received} onChange={e=>patch({received:e.target.value})}/></Field><Field label="Medio del cobro"><Select value={draft.method} onChange={e=>patch({method:e.target.value})}><option value="">Selecciona</option>{state.settings.methods.map(m=><option key={m}>{m}</option>)}</Select></Field><Field label="Dónde quedó el dinero"><Select value={draft.accountId} onChange={e=>patch({accountId:e.target.value})}><option value="">Por asignar, no incluido en saldo de una cuenta</option>{state.accounts.filter(a=>a.active&&!a.archived).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></Field><Field label="Fecha real del cobro"><Input type="date" value={draft.cashDate} onChange={e=>patch({cashDate:e.target.value})}/></Field></div>{!draft.accountId&&<p className="muted">El cobro puede guardarse con la cuenta pendiente; luego asígnala en Dinero.</p>}</Card>
  <Button type="button" variant="ghost" onClick={()=>setAdvanced(!advanced)}>{advanced?'Ocultar':'Cliente opcional, necesidad y fecha de aceptación'}</Button><div className={advanced?'stack':''} hidden={!advanced&&!!draft.accepted}><div className="form-grid"><Field label="Cliente conocido (opcional)"><Select value={draft.order.clientId||''} disabled={locked} onChange={e=>patchOrder({clientId:e.target.value||null,contactName:state.clients.find(c=>c.id===e.target.value)?.name||''})}><option value="">Venta sin cliente identificado</option>{state.clients.filter(c=>!c.archived&&!c.mergedInto).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="Nombre / referencia, si la persona lo facilita"><Input value={draft.order.contactName} disabled={locked} onChange={e=>patchOrder({contactName:e.target.value})}/></Field><Field label="Necesidad expresada"><Select value={draft.order.need} disabled={locked} onChange={e=>patchOrder({need:e.target.value as Order['need']})}>{needs.map(n=><option key={n}>{n}</option>)}</Select></Field><Field label="Fecha y hora reales de aceptación (Lima)"><Input type="datetime-local" required value={draft.accepted} disabled={locked} onChange={e=>patch({accepted:e.target.value})}/></Field></div><p className="muted">No se crea un cliente ni se autoriza publicidad a partir de una compra anónima.</p></div>
  <Field label="Referencia de contacto para cobrar, si hay saldo pendiente"><Input value={draft.reference} placeholder="Nombre y teléfono o una referencia verificable" onChange={e=>patch({reference:e.target.value})}/></Field><label className="row"><input type="checkbox" checked={draft.reviewed} onChange={e=>patch({reviewed:e.target.checked})}/>{fair.mode==='Resumen'?'Verifiqué los totales de ventas y de cobros con el respaldo indicado; un cero confirma que no hubo cobro.':'El cliente recibió este contenido con el precio indicado; verifiqué el importe y el medio realmente cobrados.'}</label><Actions><Button disabled={busy||saving||!draft.reviewed}>{saving?'Guardando…':existing?'Completar registro pendiente':'Guardar venta y cobro'}</Button><Button type="button" variant="secondary" disabled={saving} onClick={onDone}>Volver; conservar borrador</Button></Actions></form>;
}
