import {useEffect, useMemo, useState} from 'react';
import {Link, useNavigate, useSearchParams} from 'react-router-dom';
import {ArrowDownLeft, ArrowUpRight, Download, Plus, Wallet} from 'lucide-react';
import type {Account, AppState, MoneyKind, MoneyRecord, Purchase, Reconciliation, Supplier} from '../domain/types';
import {base, cents, dateLabel, dateOf, decimal, id, inPeriod, money, monthStart, normalize, today} from '../domain/helpers';
import {accountBalance, financialSummary, orderBalance, purchaseBalance} from '../domain/selectors';
import {useApp as useCRM} from '../services/store';
import {downloadBackup, exportBundle, exportCsv, exportSummaryPdf} from '../services/export';
import {useDraftState, useSessionDraft} from '../services/drafts';
import {Actions, Badge, BarChart, Button, Card, Empty, ErrorBox, Field, Form, Input, Modal, Notice, PageHeader, Select, Stat, Tabs, Textarea} from '../components/ui';

const kinds:MoneyKind[]=['Cobro','Pago','Devolución al cliente','Devolución de proveedor','Aporte','Retiro','Préstamo recibido','Pago de préstamo','Transferencia','Ajuste de saldo'];
const outgoing=(kind:MoneyKind)=>['Pago','Devolución al cliente','Retiro','Pago de préstamo','Transferencia'].includes(kind);
const clientKind=(kind:MoneyKind)=>kind==='Cobro'||kind==='Devolución al cliente';
const supplierKind=(kind:MoneyKind)=>kind==='Pago'||kind==='Devolución de proveedor';
const activeOrders=(state:AppState)=>state.orders.filter(o=>!o.archived&&!o.isSimulation&&o.status!=='Borrador'&&o.status!=='Por confirmar');
const activePurchases=(state:AppState)=>state.purchases.filter(p=>!p.archived);
const fail=(error:unknown)=>error instanceof Error?error.message:'No se pudo guardar. Conservamos tus datos para volver a intentarlo.';
const paymentLabel=(record:MoneyRecord,state:AppState)=>record.allocations.map(a=>state.orders.find(o=>o.id===a.entityId)?.code||state.purchases.find(p=>p.id===a.entityId)?.description||'Registro relacionado').join(', ');

function AttachmentsPanel({entityType,entityId}:{entityType:'money'|'purchases';entityId:string}){
  const {state,upload,readAttachment,busy}=useCRM();const [working,setWorking]=useState(false),[error,setError]=useState('');
  const files=state.attachments.filter(a=>a.entityType===entityType&&a.entityId===entityId&&!a.archived);
  return <div className="stack"><ErrorBox error={error}/><Field label="Adjuntar comprobante o evidencia" hint="PDF, imagen, texto o CSV de hasta 8 MiB. Se conserva el archivo original, sin reducir su calidad."><Input type="file" disabled={busy||working} accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');setWorking(true);try{await upload(file,entityType,entityId);}catch(e){setError(fail(e));}finally{setWorking(false);}}}/></Field>{files.length?files.map(file=><div className="list-row" key={file.id}><div className="list-main"><strong>{file.name}</strong><p>{(file.size/1024).toFixed(1)} KiB · {dateLabel(file.createdAt)}</p></div><Button variant="secondary" disabled={working} onClick={async()=>{setError('');setWorking(true);try{const blob=await readAttachment(file.path),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(b=>b.toString(16).padStart(2,'0')).join('');if(hash!==file.hash)throw new Error('El archivo no coincide con la versión registrada. Revisa su origen antes de usarlo.');const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(fail(e));}finally{setWorking(false);}}}>Descargar original</Button></div>):<Empty text="Todavía no se adjuntó evidencia a este registro."/>}<p className="muted">Adjuntar un archivo no modifica el importe ni crea otro cobro o pago.</p></div>;
}

function ActivityDetails({state,from,to,modality}:{state:AppState;from:string;to:string;modality:string}){
  const records=state.sales.filter(s=>!s.archived&&s.modality===modality).flatMap(s=>[
    ...(inPeriod(s.date,from,to)?[{id:s.id,orderId:s.orderId,date:s.date,amount:s.amount,concept:'Entrega registrada'}]:[]),
    ...s.adjustments.filter(a=>inPeriod(a.date,from,to)).map(a=>({id:a.id,orderId:s.orderId,date:a.date,amount:a.amount,concept:`Ajuste: ${a.reason}`}))
  ]).sort((a,b)=>b.date.localeCompare(a.date));
  return records.length?<div className="table-wrap"><table className="table"><thead><tr><th>Fecha / pedido</th><th>Hecho registrado</th><th>Importe</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{dateLabel(r.date)}<br/><Link className="text-link" to={`/pedidos/${r.orderId}`}>{state.orders.find(o=>o.id===r.orderId)?.code||'Pedido'}</Link></td><td>{r.concept}</td><td>{money(r.amount)}</td></tr>)}</tbody></table></div>:<Empty text="No hay entregas ni ajustes de esta actividad en el periodo."/>;
}

function MoneyForm({kind:initialKind,orderId='',purchaseId='',initial,onClose,onSaved}:{kind:MoneyKind;orderId?:string;purchaseId?:string;initial?:MoneyRecord;onClose:()=>void;onSaved:()=>void}){
  const {state,run,busy}=useCRM();const draftScope=`money:${initial?.id||orderId||purchaseId||initialKind}`;
  const [kind,setKind,clearDraft]=useDraftState<MoneyKind>(draftScope,'kind',initial?.kind||initialKind);
  const [date,setDate]=useDraftState(draftScope,'date',initial?.date||today());
  const presetEntity=orderId||purchaseId;
  const presetOrder=state.orders.find(o=>o.id===orderId),presetPurchase=state.purchases.find(p=>p.id===purchaseId);
  const presetAmount=presetOrder?Math.abs(orderBalance(state,presetOrder)):presetPurchase?Math.abs(purchaseBalance(state,presetPurchase)):null;
  const [amount,setAmount]=useDraftState(draftScope,'amount',initial?decimal(initial.amount):presetAmount!==null?decimal(presetAmount):'');
  const [accountId,setAccountId]=useDraftState(draftScope,'accountId',initial?.accountId||'');
  const [toAccountId,setToAccountId]=useDraftState(draftScope,'toAccountId',initial?.toAccountId||'');
  const [method,setMethod]=useDraftState(draftScope,'method',initial?.method||'');
  const [reference,setReference]=useDraftState(draftScope,'reference',initial?.reference||'');
  const [notes,setNotes]=useDraftState(draftScope,'notes',initial?`Corrección de ${initial.id}. ${initial.notes}`:'');
  const [direction,setDirection]=useDraftState<'Entrada'|'Salida'>(draftScope,'direction',initial?.direction||'Entrada');
  const [allowCredit,setAllowCredit]=useDraftState(draftScope,'allowCredit',false);
  const [allocations,setAllocations]=useDraftState<{entityId:string;value:string}[]>(draftScope,'allocations',initial?initial.allocations.map(a=>({entityId:a.entityId,value:decimal(a.amount)})):presetEntity?[{entityId:presetEntity,value:decimal(presetAmount)}]:[{entityId:'',value:''}]);
  const [error,setError]=useState('');
  const entities=clientKind(kind)?activeOrders(state).map(o=>({id:o.id,label:`${o.code} · ${o.contactName||'Venta presencial'} · ${money(orderBalance(state,o))}`})):activePurchases(state).map(p=>({id:p.id,label:`${p.description} · ${money(purchaseBalance(state,p))}`}));
  const needsAllocation=clientKind(kind)||supplierKind(kind);
  function changeKind(value:MoneyKind){setKind(value);setAllocations([{entityId:'',value:''}]);setAllowCredit(false);setError('');}
  async function submit(){
    setError('');
    try{
      const parsed=cents(amount);if(parsed<=0)throw new Error('El importe debe ser mayor que cero.');
      if(!date||!method.trim())throw new Error('Indica la fecha real y el medio de pago de la operación.');
      if(kind==='Transferencia'&&(!accountId||!toAccountId||accountId===toAccountId))throw new Error('Elige dos cuentas distintas para la transferencia.');
      const applied=needsAllocation?allocations.filter(a=>a.entityId).map(a=>({entityId:a.entityId,amount:cents(a.value)})):[];
      if(needsAllocation&&!applied.length)throw new Error('Vincula el dinero con el pedido o la compra correspondiente.');
      if(applied.some(a=>!entities.some(e=>e.id===a.entityId)))throw new Error('El pedido o la compra relacionados ya no están disponibles. Elige un registro válido.');
      if(applied.some(a=>a.amount<=0))throw new Error('Cada aplicación de dinero debe ser mayor que cero.');
      if(new Set(applied.map(a=>a.entityId)).size!==applied.length)throw new Error('Un registro sólo debe aparecer una vez en la distribución.');
      const assigned=applied.reduce((sum,a)=>sum+a.amount,0);if(needsAllocation&&assigned!==parsed)throw new Error('Distribuye el importe completo entre sus pedidos o compras. La suma debe coincidir con la operación.');
      if((kind==='Ajuste de saldo'||kind==='Préstamo recibido'||kind==='Pago de préstamo')&&!notes.trim())throw new Error('Explica el motivo y la referencia de esta operación.');
      const record:MoneyRecord={...base(),kind,amount:parsed,date,accountId:accountId||null,toAccountId:kind==='Transferencia'?toAccountId:null,method:method.trim(),reference:reference.trim(),notes:notes.trim(),allocations:applied,reversalOf:null,reversedBy:null,direction:kind==='Ajuste de saldo'?direction:outgoing(kind)?'Salida':'Entrada',requestId:id()};
      await run({type:'recordMoney',record,allowCredit});clearDraft();onSaved();
    }catch(e){setError(fail(e));}
  }
  return <Form onSubmit={submit}><p className="muted">El borrador se conserva en esta sesión hasta registrar la operación.</p><ErrorBox error={error}/><div className="form-grid">
    <Field label="Operación"><Select value={kind} onChange={e=>changeKind(e.target.value as MoneyKind)}>{kinds.map(k=><option key={k}>{k}</option>)}</Select></Field>
    <Field label="Fecha real"><Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field>
    <Field label="Importe en soles" hint="Escribe los céntimos con dos decimales, por ejemplo 125.50."><Input data-modal-first inputMode="decimal" required value={amount} onChange={e=>{setAmount(e.target.value);if(allocations.length===1)setAllocations([{...allocations[0],value:e.target.value}]);}} placeholder="0.00"/></Field>
    <Field label={kind==='Transferencia'?'Cuenta de origen':outgoing(kind)?'Cuenta de salida':'Cuenta de destino'} hint="Si todavía no sabes la cuenta, queda visible para revisar; no se inventa un saldo."><Select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Cuenta por identificar</option>{state.accounts.filter(a=>a.active&&!a.archived).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</Select></Field>
    {kind==='Transferencia'&&<Field label="Cuenta de destino"><Select required value={toAccountId} onChange={e=>setToAccountId(e.target.value)}><option value="">Elegir cuenta</option>{state.accounts.filter(a=>a.active&&!a.archived&&a.id!==accountId).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></Field>}
    {kind==='Ajuste de saldo'&&<Field label="Efecto del ajuste"><Select value={direction} onChange={e=>setDirection(e.target.value as 'Entrada'|'Salida')}><option>Entrada</option><option>Salida</option></Select></Field>}
    <Field label="Medio de pago"><Input required list="money-methods" value={method} onChange={e=>setMethod(e.target.value)} placeholder="Según el medio usado realmente"/><datalist id="money-methods">{state.settings.methods.map(m=><option key={m} value={m}/>)}</datalist></Field>
    <Field label="Referencia de operación"><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Referencia del comprobante, si existe"/></Field>
  </div>
  {needsAllocation&&<section className="form-section"><h3>{clientKind(kind)?'Pedidos relacionados':'Compras relacionadas'}</h3><p className="muted">El dinero se registra una sola vez. Esta distribución indica a qué compromiso se aplica.</p>{allocations.map((a,index)=><div className="form-grid" key={index}>
    <Field label={clientKind(kind)?'Pedido':'Compra'}><Select value={a.entityId} onChange={e=>setAllocations(old=>old.map((v,i)=>i===index?{...v,entityId:e.target.value,value:old.length===1?amount:v.value}:v))}><option value="">Elegir registro</option>{entities.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</Select></Field>
    <Field label="Importe aplicado"><div className="row"><Input inputMode="decimal" value={a.value} onChange={e=>setAllocations(old=>old.map((v,i)=>i===index?{...v,value:e.target.value}:v))}/>{allocations.length>1&&<Button type="button" variant="ghost" onClick={()=>setAllocations(old=>old.filter((_,i)=>i!==index))}>Quitar</Button>}</div></Field>
  </div>)}<Button type="button" variant="secondary" onClick={()=>setAllocations(old=>[...old,{entityId:'',value:''}])}><Plus size={16}/>Distribuir entre otro registro</Button>
  {(kind==='Cobro'||kind==='Pago')&&<label className="row"><input type="checkbox" checked={allowCredit} onChange={e=>setAllowCredit(e.target.checked)}/>Confirmo el exceso sobre el saldo pendiente; quedará como saldo a favor del cliente o del negocio, vinculado al registro.</label>}</section>}
  <Field label="Nota y motivo"><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field>
  {!accountId&&kind!=='Transferencia'&&<Notice tone="warning">La operación quedará con cuenta por identificar. Tendrás que asignarla antes de interpretar los saldos de cuentas.</Notice>}
  {kind==='Devolución al cliente'&&<Notice>Registra aquí la salida real. Una cancelación o descuento comercial se acuerda en el pedido; devolver dinero no borra el cobro original.</Notice>}
  {initial&&<Notice tone="warning">La operación anterior ya fue revertida. Este formulario registra una operación nueva; si vuelves, la reversión se conserva.</Notice>}
  <Actions><Button type="button" variant="secondary" onClick={onClose}>Volver</Button><Button disabled={busy} type="submit">{busy?'Guardando…':'Registrar operación'}</Button></Actions></Form>;
}

function PurchaseForm({initial,eventId='',needId='',onClose,onSaved}:{initial?:Purchase;eventId?:string;needId?:string;onClose:()=>void;onSaved:(id:string,pay:boolean)=>void}){
  const {state,save,run,busy}=useCRM();const draftScope=`purchase:${initial?.id||needId||eventId||'new'}`;
  const need=state.purchaseNeeds.find(n=>n.id===needId);
  const [draft,setDraft,clearDraft]=useSessionDraft<Purchase>(draftScope,initial||{...base(),description:need?.name||'',amount:0,businessAmount:0,date:today(),category:'Ingredientes',supplierId:need?state.suppliers.find(s=>normalize(s.name)===normalize(need.supplier)&&!s.archived)?.id||null:null,dueDate:'',orderIds:need?.orderIds||[],eventId:eventId||null,quantity:need?Math.max(0,need.quantity-need.purchased):null,unit:need?.unit||'',notes:need?[need.notes,need.supplier?`Proveedor previsto: ${need.supplier}`:''].filter(Boolean).join('\n'):'',status:'Vigente',adjustments:[],allocations:[]});
  const [amount,setAmount]=useDraftState(draftScope,'amount',initial?decimal(initial.amount):'');
  const [business,setBusiness]=useDraftState(draftScope,'business',initial?decimal(initial.businessAmount):'');
  const [allocations,setAllocations]=useDraftState<{orderId:string;value:string;method:string}[]>(draftScope,'allocations',initial?.allocations.map(a=>({orderId:a.orderId,value:decimal(a.amount),method:a.method}))||[]);
  const [pay,setPay]=useDraftState(draftScope,'pay',false),[reason,setReason]=useDraftState(draftScope,'reason',''),[error,setError]=useState('');
  const update=<K extends keyof Purchase>(key:K,value:Purchase[K])=>setDraft(d=>({...d,[key]:value}));
  const eligibleOrders=state.orders.filter(o=>!o.archived&&!o.isSimulation);
  async function submit(){
    setError('');
    try{
      const total=cents(amount),part=business.trim()?cents(business):total;
      if(total<=0||part<0||part>total)throw new Error('Revisa el total y la parte atribuible al negocio.');
      if(!draft.description.trim()||!draft.date||!draft.category.trim())throw new Error('Completa el concepto, la fecha y la categoría.');
      if(initial&&(initial.amount!==total||initial.businessAmount!==part||initial.date!==draft.date))throw new Error('La compra original se conserva. Para cambiar su importe usa Ajustar compra.');
      if(draft.quantity!==null&&draft.quantity<=0)throw new Error('La cantidad comprada debe ser mayor que cero, o quedar sin confirmar.');
      const apportioned=allocations.map(a=>({orderId:a.orderId,amount:cents(a.value),method:a.method.trim()}));
      if(apportioned.some(a=>!eligibleOrders.some(o=>o.id===a.orderId)||a.amount<=0||!a.method))throw new Error('Cada reparto requiere un pedido válido, un importe positivo y el criterio utilizado.');
      if(new Set(apportioned.map(a=>a.orderId)).size!==apportioned.length)throw new Error('Un pedido debe aparecer una sola vez en el reparto.');
      if(apportioned.reduce((sum,a)=>sum+a.amount,0)>part)throw new Error('El reparto de costos excede la parte atribuible al negocio.');
      if(initial&&!reason.trim())throw new Error('Explica por qué corriges esta compra.');
      const record:Purchase={...draft,amount:total,businessAmount:part,description:draft.description.trim(),allocations:apportioned,orderIds:[...new Set([...draft.orderIds,...apportioned.map(a=>a.orderId)])]};
      if(!initial&&needId){
        if(!need)throw new Error('La necesidad de compra ya no existe. Vuelve a la agenda y revisa sus datos.');
        if(draft.unit!==need.unit||draft.quantity===null||draft.quantity<=0)throw new Error('Registra la cantidad real comprada en la misma unidad de la necesidad.');
        await run({type:'purchaseWithNeed',purchase:record,needId,quantity:draft.quantity});
      }else await save('purchases',record,reason||'Compra registrada');
      clearDraft();onSaved(draft.id,pay);
    }catch(e){setError(fail(e));}
  }
  return <Form onSubmit={submit}><ErrorBox error={error}/>
  {need&&!initial&&<Notice>Necesidad: <strong>{need.name}</strong>. Pendiente: {Math.max(0,need.quantity-need.purchased)} {need.unit}. Ajusta la cantidad al importe realmente adquirido; la compra y su avance se guardan juntos.</Notice>}
  <div className="form-grid">
    <div className="span-2"><Field label="Qué se compró o comprometió"><Input data-modal-first required value={draft.description} onChange={e=>update('description',e.target.value)}/></Field></div>
    <Field label="Importe total en soles"><Input required inputMode="decimal" readOnly={!!initial} value={amount} onChange={e=>setAmount(e.target.value)}/></Field>
    <Field label="Parte del negocio" hint="Deja vacío para usar todo el importe. No se aplica un porcentaje por defecto."><Input inputMode="decimal" readOnly={!!initial} value={business} onChange={e=>setBusiness(e.target.value)}/></Field>
    <Field label="Fecha de compra"><Input required readOnly={!!initial} type="date" value={draft.date} onChange={e=>update('date',e.target.value)}/></Field>
    <Field label="Fecha de pago acordada"><Input type="date" value={draft.dueDate} onChange={e=>update('dueDate',e.target.value)}/></Field>
    <Field label="Categoría"><Input list="purchase-categories" required value={draft.category} onChange={e=>update('category',e.target.value)}/><datalist id="purchase-categories">{state.settings.categories.map(c=><option key={c}>{c}</option>)}</datalist></Field>
    <Field label="Proveedor"><Select value={draft.supplierId||''} onChange={e=>update('supplierId',e.target.value||null)}><option value="">Por identificar</option>{state.suppliers.filter(s=>!s.archived).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></Field>
    <Field label="Cantidad realmente adquirida"><Input type="number" min="0.000001" step="any" value={draft.quantity??''} onChange={e=>update('quantity',e.target.value?Number(e.target.value):null)}/></Field>
    <Field label="Unidad"><Input readOnly={!!need&&!initial} value={draft.unit} onChange={e=>update('unit',e.target.value)} placeholder="kg, unidades, horas…"/></Field>
    <Field label="Feria o evento relacionado"><Select value={draft.eventId||''} onChange={e=>update('eventId',e.target.value||null)}><option value="">Sin evento</option>{state.fairs.filter(f=>!f.archived).map(f=><option key={f.id} value={f.id}>{f.name} · {dateLabel(f.date)}</option>)}</Select></Field>
    <Field label="Nota y fuente"><Textarea value={draft.notes} onChange={e=>update('notes',e.target.value)} placeholder="Condición del proveedor, comprobante o reparto doméstico"/></Field>
  </div>
  <section className="form-section"><h3>Pedidos relacionados</h3><p className="muted">Relacionar un pedido no le atribuye automáticamente todo el gasto.</p><div className="form-grid">{eligibleOrders.map(o=><label className="row" key={o.id}><input type="checkbox" checked={draft.orderIds.includes(o.id)} onChange={e=>update('orderIds',e.target.checked?[...draft.orderIds,o.id]:draft.orderIds.filter(v=>v!==o.id))}/>{o.code} · {o.contactName||'Venta presencial'}</label>)}</div></section>
  <section className="form-section"><h3>Reparto del costo entre pedidos</h3><p className="muted">Reparte sólo el importe que puedes justificar. No duplica el pago y puede ser menor que el gasto del negocio.</p>
  {allocations.map((a,index)=><div className="form-grid" key={index}>
    <Field label="Pedido"><Select required value={a.orderId} onChange={e=>setAllocations(old=>old.map((v,i)=>i===index?{...v,orderId:e.target.value}:v))}><option value="">Elegir pedido</option>{eligibleOrders.map(o=><option key={o.id} value={o.id}>{o.code} · {o.contactName}</option>)}</Select></Field>
    <Field label="Importe atribuible en soles"><Input required inputMode="decimal" value={a.value} onChange={e=>setAllocations(old=>old.map((v,i)=>i===index?{...v,value:e.target.value}:v))}/></Field>
    <Field label="Criterio utilizado"><Input required value={a.method} onChange={e=>setAllocations(old=>old.map((v,i)=>i===index?{...v,method:e.target.value}:v))} placeholder="Cantidad usada, horas u otro criterio comprobado"/></Field>
    <Button type="button" variant="ghost" onClick={()=>setAllocations(old=>old.filter((_,i)=>i!==index))}>Quitar reparto</Button>
  </div>)}
  <Button type="button" variant="secondary" onClick={()=>setAllocations(old=>[...old,{orderId:'',value:'',method:''}])}>Añadir reparto</Button></section>
  {initial&&<Field label="Motivo de la corrección"><Input required value={reason} onChange={e=>setReason(e.target.value)}/></Field>}
  {!initial&&<label className="row"><input type="checkbox" checked={pay} onChange={e=>setPay(e.target.checked)}/>Después de guardar, registrar el pago total o parcial.</label>}
  {initial&&initial.adjustments.length>0&&<section className="form-section"><h3>Ajustes conservados</h3>{initial.adjustments.map((a,index)=><div className="list-row" key={index}><div className="list-main"><strong>{dateLabel(a.date)} · {money(a.amount)}</strong><p>{a.reason}</p></div></div>)}</section>}
  <Notice>La compra crea una obligación. Sólo registrar un pago crea una salida de dinero. Los costos de receta se revisan por separado.</Notice>
  <Actions><Button variant="secondary" type="button" onClick={onClose}>Volver</Button><Button type="submit" disabled={busy}>{busy?'Guardando…':pay?'Guardar y registrar pago':'Guardar compra'}</Button></Actions></Form>;
}

function SupplierForm({initial,onClose}:{initial?:Supplier;onClose:()=>void}){const {save,busy}=useCRM();const draftScope=`supplier:${initial?.id||'new'}`;const [draft,setDraft,clearDraft]=useSessionDraft<Supplier>(draftScope,initial||{...base(),name:'',contact:'',supplies:'',conditions:'',notes:''});const [error,setError]=useState('');return <Form onSubmit={async()=>{try{if(!draft.name.trim())throw new Error('Escribe el nombre o referencia del proveedor.');await save('suppliers',draft,'Proveedor y condiciones revisados');clearDraft();onClose();}catch(e){setError(fail(e));}}}><ErrorBox error={error}/><Field label="Proveedor"><Input data-modal-first required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Contacto"><Input value={draft.contact} onChange={e=>setDraft({...draft,contact:e.target.value})}/></Field><Field label="Qué suministra"><Input value={draft.supplies} onChange={e=>setDraft({...draft,supplies:e.target.value})}/></Field><Field label="Condiciones comunicadas"><Textarea value={draft.conditions} onChange={e=>setDraft({...draft,conditions:e.target.value})}/></Field><Field label="Notas"><Textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><Actions><Button type="button" variant="secondary" onClick={onClose}>Volver</Button><Button disabled={busy}>Guardar proveedor</Button></Actions></Form>;}

function AccountForm({initial,onClose}:{initial?:Account;onClose:()=>void}){
  const {state,save,busy}=useCRM();const draftScope=`account:${initial?.id||'new'}`;
  const [draft,setDraft,clearDraft]=useSessionDraft<Account>(draftScope,initial||{...base(),name:'',opening:null,openingDate:today(),source:'',active:true});
  const [opening,setOpening]=useDraftState(draftScope,'opening',decimal(initial?.opening)),[reason,setReason]=useDraftState(draftScope,'reason',''),[error,setError]=useState('');
  const hasMovements=!!initial&&state.money.some(m=>m.accountId===initial.id||m.toAccountId===initial.id);
  const openingLocked=hasMovements&&initial?.opening!==null;
  return <Form onSubmit={async()=>{
    setError('');try{
      if(!draft.name.trim())throw new Error('Escribe el nombre de la cuenta.');
      const value=opening.trim()?cents(opening):null;
      if(value!==null&&(!draft.openingDate||!draft.source.trim()))throw new Error('Un saldo inicial conocido requiere fecha y fuente.');
      if(openingLocked&&(value!==initial!.opening||draft.openingDate!==initial!.openingDate))throw new Error('La apertura conocida con movimientos se conserva. Registra una corrección de saldo fechada.');
      if(hasMovements&&initial?.opening===null&&value!==null&&!reason.trim())throw new Error('Explica cómo verificaste el saldo inicial antes desconocido.');
      await save('accounts',{...draft,name:draft.name.trim(),opening:value},reason.trim()||'Cuenta y fuente de saldo revisadas');clearDraft();onClose();
    }catch(e){setError(fail(e));}
  }}><ErrorBox error={error}/>
  <Field label="Nombre de cuenta o caja"><Input data-modal-first required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Nombre que ambas reconozcan"/></Field>
  <Field label="Saldo inicial en soles" hint="Vacío significa desconocido, no cero."><Input readOnly={openingLocked} inputMode="decimal" value={opening} onChange={e=>setOpening(e.target.value)}/></Field>
  <Field label="Fecha del saldo inicial"><Input readOnly={openingLocked} type="date" value={draft.openingDate} onChange={e=>setDraft({...draft,openingDate:e.target.value})}/></Field>
  <Field label="Fuente del saldo"><Textarea value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})} placeholder="Saldo contado o consulta de cuenta; fecha y documento de referencia"/></Field>
  {hasMovements&&initial?.opening===null&&<Field label="Motivo de la apertura verificada"><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Cómo y a qué fecha se verificó el saldo antes desconocido"/></Field>}
  <label className="row"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Cuenta activa</label>
  {openingLocked&&<Notice tone="warning">Esta cuenta tiene movimientos; su apertura conocida y fecha se conservan. Investiga las diferencias mediante una comparación y registra un ajuste de saldo con fecha y motivo cuando corresponda.</Notice>}
  {hasMovements&&initial?.opening===null&&<Notice>Define un saldo contado o comprobado a una fecha concreta. No uses el movimiento neto como si fuera el saldo de apertura.</Notice>}
  <Actions><Button type="button" variant="secondary" onClick={onClose}>Volver</Button><Button disabled={busy}>Guardar cuenta</Button></Actions></Form>;
}

function ReconciliationForm({onClose}:{onClose:()=>void}){const {state,save,busy}=useCRM();const draftScope='reconciliation:new';const [accountId,setAccountId,clearDraft]=useDraftState(draftScope,'accountId','');const [date,setDate]=useDraftState(draftScope,'date',today());const [counted,setCounted]=useDraftState(draftScope,'counted','');const [notes,setNotes]=useDraftState(draftScope,'notes','');const [error,setError]=useState('');const account=state.accounts.find(a=>a.id===accountId);const calculated=account?accountBalance(state,account,date):null;return <Form onSubmit={async()=>{try{if(!account)throw new Error('Selecciona una cuenta.');const record:Reconciliation={...base(),accountId,date,counted:cents(counted),calculated,notes};await save('reconciliations',record,'Saldo contado y calculado comparados');clearDraft();onClose();}catch(e){setError(fail(e));}}}><ErrorBox error={error}/><Field label="Cuenta"><Select required value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Elegir cuenta</option>{state.accounts.filter(a=>!a.archived).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></Field><Field label="Fecha de comparación"><Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Saldo contado o consultado en soles"><Input required inputMode="decimal" value={counted} onChange={e=>setCounted(e.target.value)}/></Field><Notice>Saldo registrado al corte: <strong>{money(calculated)}</strong>. Una diferencia se investiga; guardar esta comparación no crea una venta ni ajusta dinero.</Notice><Field label="Fuente y observaciones"><Textarea required value={notes} onChange={e=>setNotes(e.target.value)}/></Field><Actions><Button type="button" variant="secondary" onClick={onClose}>Volver</Button><Button disabled={busy}>Guardar comparación</Button></Actions></Form>;}

function PurchaseAdjustment({purchase,onClose}:{purchase:Purchase;onClose:()=>void}){const {run,busy}=useCRM();const draftScope=`purchase-adjust:${purchase.id}`;const [amount,setAmount,clearDraft]=useDraftState(draftScope,'amount','');const [date,setDate]=useDraftState(draftScope,'date',today());const [reason,setReason]=useDraftState(draftScope,'reason','');const [cancel,setCancel]=useDraftState(draftScope,'cancel',false);const [error,setError]=useState('');return <Form onSubmit={async()=>{try{if(!reason.trim())throw new Error('Explica el ajuste acordado.');await run({type:'purchaseAdjustment',id:purchase.id,amount:cancel?0:cents(amount),date,reason,cancel});clearDraft();onClose();}catch(e){setError(fail(e));}}}><ErrorBox error={error}/><Notice>Compra: {purchase.description}. El importe original y los pagos se conservan. Si el proveedor devuelve dinero, registra la devolución real por separado.</Notice><Field label="Fecha del acuerdo"><Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field><label className="row"><input type="checkbox" checked={cancel} onChange={e=>setCancel(e.target.checked)}/>Cancelar la obligación completa, sin cargo acordado.</label>{!cancel&&<Field label="Cambio del importe en soles" hint="Usa un signo negativo para una reducción, por ejemplo -20.00."><Input inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)}/></Field>}<Field label="Motivo y acuerdo"><Textarea required value={reason} onChange={e=>setReason(e.target.value)}/></Field><Actions><Button variant="secondary" type="button" onClick={onClose}>Volver</Button><Button disabled={busy}>Guardar ajuste</Button></Actions></Form>;}

function MoneyRows({records,onCorrect,onAssign,onFiles}:{records:MoneyRecord[];onCorrect:(r:MoneyRecord)=>void;onAssign:(r:MoneyRecord)=>void;onFiles:(r:MoneyRecord)=>void}){const {state}=useCRM();return records.length?<div className="table-wrap"><table className="table"><thead><tr><th>Fecha</th><th>Operación</th><th>Importe</th><th>Cuenta</th><th>Aplicación</th><th>Acciones</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{dateLabel(r.date)}</td><td><strong>{r.kind}</strong><br/><small>{r.method||'Medio por registrar'}{r.reference?` · ${r.reference}`:''}</small>{r.reversedBy&&<Badge tone="danger">Revertido</Badge>}{r.reversalOf&&<Badge>Reversión</Badge>}</td><td>{money((r.direction==='Salida'?-1:1)*r.amount)}</td><td>{state.accounts.find(a=>a.id===r.accountId)?.name||'Por identificar'}{r.toAccountId&&<> → {state.accounts.find(a=>a.id===r.toAccountId)?.name||'Cuenta'}</>}</td><td>{paymentLabel(r,state)||r.notes||'Movimiento del negocio'}</td><td><div className="inline-actions"><Button variant="ghost" onClick={()=>onFiles(r)}>Archivos</Button></div>{!r.reversedBy&&!r.reversalOf&&<div className="inline-actions">{!r.accountId&&<Button variant="secondary" onClick={()=>onAssign(r)}>Asignar cuenta</Button>}<Button variant="ghost" onClick={()=>onCorrect(r)}>Corregir</Button></div>}</td></tr>)}</tbody></table></div>:<Empty text="Los movimientos aparecerán al registrar dinero real recibido o pagado."/>;}

function OperationTools({records}:{records:MoneyRecord[]}){const {state,run,busy}=useCRM();const [correct,setCorrect]=useDraftState<MoneyRecord|null>('money-tools','correct',null);const [files,setFiles]=useState<string|null>(null);const [assign,setAssign]=useDraftState<MoneyRecord|null>('money-tools','assign',null);const [replacement,setReplacement]=useDraftState<MoneyRecord|null>('money-tools','replacement',null);const [reason,setReason,clearCorrection]=useDraftState(`correction:${correct?.id||'closed'}`,'reason','');const [date,setDate]=useDraftState(`correction:${correct?.id||'closed'}`,'date',today());const [account,setAccount,clearAssignment]=useDraftState(`assign-account:${assign?.id||'closed'}`,'account','');const [replace,setReplace]=useDraftState(`correction:${correct?.id||'closed'}`,'replace',true);const [error,setError]=useState('');return <>
  <MoneyRows records={records} onFiles={r=>setFiles(r.id)} onCorrect={r=>{setCorrect(r);setError('');}} onAssign={r=>{setAssign(r);setError('');}}/>
  <Modal open={!!correct} onClose={()=>setCorrect(null)} title="Corregir operación" description="El original queda en el historial; una reversión evita borrar dinero sin rastro.">{correct&&<Form onSubmit={async()=>{try{if(!reason.trim())throw new Error('Explica la corrección.');await run({type:'reverseMoney',id:correct.id,date,reason});clearCorrection();const source=correct;setCorrect(null);if(replace)setReplacement(source);}catch(e){setError(fail(e));}}}><ErrorBox error={error}/><Notice>{correct.kind} de {money(correct.amount)} · {dateLabel(correct.date)}</Notice><Field label="Fecha de la corrección"><Input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Motivo"><Textarea required value={reason} onChange={e=>setReason(e.target.value)}/></Field><label className="row"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>Abrir una operación nueva con los datos correctos después de revertir.</label><Actions><Button variant="secondary" type="button" onClick={()=>setCorrect(null)}>Volver</Button><Button variant="danger" disabled={busy}>Revertir operación</Button></Actions></Form>}</Modal>
  <Modal open={!!assign} onClose={()=>setAssign(null)} title="Identificar cuenta">{assign&&<Form onSubmit={async()=>{try{if(!account)throw new Error('Selecciona la cuenta real.');await run({type:'assignAccount',id:assign.id,accountId:account});clearAssignment();setAssign(null);}catch(e){setError(fail(e));}}}><ErrorBox error={error}/><Notice>{assign.kind} · {money(assign.amount)}. No se registra otra entrada o salida.</Notice><Field label="Cuenta real"><Select required value={account} onChange={e=>setAccount(e.target.value)}><option value="">Elegir cuenta</option>{state.accounts.filter(a=>!a.archived&&a.active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></Field><Actions><Button variant="secondary" type="button" onClick={()=>setAssign(null)}>Volver</Button><Button disabled={busy}>Guardar cuenta</Button></Actions></Form>}</Modal>
  <Modal open={!!files} onClose={()=>setFiles(null)} title="Comprobantes y evidencia">{files&&<AttachmentsPanel entityType="money" entityId={files}/>}</Modal>
  <Modal open={!!replacement} onClose={()=>setReplacement(null)} title="Registrar operación corregida" wide>{replacement&&<MoneyForm kind={replacement.kind} initial={replacement} onClose={()=>setReplacement(null)} onSaved={()=>setReplacement(null)}/>}</Modal>
  </>;}

export function MoneyScreen(){
  const {state,notify}=useCRM();const navigate=useNavigate();const [params,setParams]=useSearchParams();const [from,setFrom]=useState(monthStart());const [to,setTo]=useState(today());const [tab,setTab]=useState('resumen');const [activityFilter,setActivityFilter]=useState('');const [purchaseFiles,setPurchaseFiles]=useState<string|null>(null);
  const [operation,setOperation]=useState<{kind:MoneyKind;orderId?:string;purchaseId?:string}|null>(null);const [purchase,setPurchase]=useState<Purchase|'new'|null>(null);const [eventId,setEventId]=useState('');const [needId,setNeedId]=useState('');const [supplier,setSupplier]=useState<Supplier|'new'|null>(null);const [account,setAccount]=useState<Account|'new'|null>(null);const [reconcile,setReconcile]=useState(false);const [adjust,setAdjust]=useState<Purchase|null>(null);const [error,setError]=useState('');
  const serialized=params.toString();useEffect(()=>{const action=params.get('action');if(action==='cobro')setOperation({kind:'Cobro',orderId:params.get('order')||undefined});if(action==='pago')setOperation({kind:'Pago',purchaseId:params.get('purchase')||undefined});if(action==='compra'){setEventId(params.get('event')||'');setNeedId(params.get('need')||'');setPurchase('new');}},[serialized]);
  const closeAction=()=>{setOperation(null);setPurchase(null);const p=new URLSearchParams(params);p.delete('action');p.delete('order');p.delete('purchase');p.delete('event');p.delete('need');setNeedId('');setEventId('');setParams(p,{replace:true});};
  const valid=!!from&&!!to&&from<=to;const summary=financialSummary(state,valid?from:to,to);const orders=activeOrders(state);const purchases=activePurchases(state);const records=state.money.filter(r=>!r.archived&&inPeriod(r.date,from,to)).sort((a,b)=>b.date.localeCompare(a.date));
  const activityRows=['Productos','Catering'].map(modality=>({label:modality,value:state.sales.filter(s=>!s.archived&&s.modality===modality).reduce((sum,s)=>sum+(inPeriod(s.date,from,to)?s.amount:0)+s.adjustments.filter(a=>inPeriod(a.date,from,to)).reduce((n,a)=>n+a.amount,0),0)}));
  const exportAction=async(task:()=>unknown)=>{try{if(!from||!to||from>to)throw new Error('Revisa las fechas del periodo.');await task();notify('Archivo preparado para descargar.');}catch(e){setError(fail(e));}};
  return <div className="stack"><PageHeader eyebrow="Dinero claro" title="Dinero" description="Ventas, cobros y pagos son hechos distintos. Cada cifra se puede revisar en sus registros." actions={<><Button onClick={()=>setOperation({kind:'Cobro'})}><Plus size={18}/>Registrar dinero</Button><Button variant="secondary" onClick={()=>{setEventId('');setNeedId('');setPurchase('new');}}>Compra o gasto</Button></>}/>
  <div className="toolbar"><Field label="Desde"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Hasta / corte"><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><Link className="btn btn-secondary" to="/dinero/cierre"><Download size={16}/>Revisar y exportar</Link><Link className="btn btn-secondary" to="/costos">Costos y precios</Link></div>
  <p className="muted">Todas las actividades · Última actualización: {dateLabel(state.updatedAt)}. Los saldos se calculan al corte seleccionado.</p>{!valid&&<Notice tone="warning">La fecha inicial debe estar antes de la fecha final.</Notice>}<ErrorBox error={error}/>
  <Tabs value={tab} onChange={setTab} values={[{id:'resumen',label:'Resumen'},{id:'pendientes',label:'Por cobrar y pagar'},{id:'compras',label:'Compras y proveedores'},{id:'cuentas',label:'Cuentas y revisión'}]}/>
  {tab==='resumen'&&<><div className="stat-grid"><Stat label="Ventas entregadas" value={money(summary.sales)} detail="Entregas del periodo y ajustes comerciales" icon={<Wallet size={18}/>}/><Stat label="Cobros de clientes" value={money(summary.receipts)} detail={<>Adelantos por entregar: {money(summary.advances)} · Devoluciones: {money(summary.refunds)}</>} icon={<ArrowDownLeft size={18}/>}/><Stat label="Pagos del negocio" value={money(summary.payments)} detail={<>Devoluciones de proveedores: {money(summary.providerRefunds)}</>} icon={<ArrowUpRight size={18}/>}/><Stat label="Por cobrar al corte" value={money(summary.receivable)} detail={<>Entregado: {money(summary.deliveredDue)} · Por entregar: {money(summary.futureDue)}</>}/></div>
  <div className="split-grid"><Card title="Actividad entregada" subtitle={`${dateLabel(from)} – ${dateLabel(to)}`}><BarChart rows={activityRows.map(row=>({...row,onClick:()=>setActivityFilter(row.label)}))} label="Ventas entregadas por actividad" format={money}/><p className="muted">Incluye los ajustes registrados durante el periodo, aunque la entrega haya sido anterior. Un importe negativo refleja reducciones; los pedidos futuros se muestran por separado.</p></Card><Card title="Lo que sigue"><div className="list-row"><div className="list-main"><strong>Obligaciones por pagar</strong><p>{money(summary.payable)} al corte</p></div><Button variant="secondary" onClick={()=>setTab('pendientes')}>Ver pendientes</Button></div><div className="list-row"><div className="list-main"><strong>Saldos a favor de clientes</strong><p>{money(summary.credit)} por aplicar o devolver</p></div><Button variant="secondary" onClick={()=>setTab('pendientes')}>Revisar</Button></div><Notice>Movimiento operativo neto: <strong>{money(summary.net)}</strong>. No es utilidad ni saldo de caja.</Notice></Card></div>
  {activityFilter&&<Card title={`Detalle de ${activityFilter.toLowerCase()}`} action={<Button variant="ghost" onClick={()=>setActivityFilter('')}>Cerrar detalle</Button>}><ActivityDetails state={state} from={from} to={to} modality={activityFilter}/></Card>}
  <Card title="Entradas y salidas operativas" subtitle="Cobros y pagos del periodo, netos de correcciones; incluye devoluciones"><BarChart rows={[{label:'Entradas',value:summary.receipts+summary.providerRefunds,onClick:()=>navigate(`/dinero/movimientos?from=${from}&to=${to}&direction=Entrada&operational=true`)},{label:'Salidas',value:summary.payments+summary.refunds,onClick:()=>navigate(`/dinero/movimientos?from=${from}&to=${to}&direction=Salida&operational=true`)}]} format={money} label="Entradas y salidas operativas"/><p className="muted">Las transferencias, aportes y préstamos se revisan por separado. Haz clic para ver los movimientos que componen cada cifra.</p></Card>
  <Card title="Resultado estimado de pedidos" subtitle={`${summary.reviewedCount} de ${summary.deliveredCount} pedidos entregados con costos revisados`} action={<Link className="text-link" to="/costos">Revisar costos</Link>}><strong>{summary.reviewedCount?money(summary.estimated):'Sin costos revisados'}</strong><p className="muted">Ventas y costos del mismo conjunto de pedidos revisados. No se extrapola a pedidos sin costo completo ni se llama utilidad neta.</p></Card>
  <Card title="Movimientos del periodo" action={<Link className="text-link" to="/dinero/movimientos">Ver todos y corregir</Link>}><OperationTools records={records.slice(0,12)}/></Card></>}
  {tab==='pendientes'&&<div className="split-grid"><Card title="Clientes: por cobrar o devolver" subtitle={`Compromisos vigentes al ${dateLabel(to)}`}>
    {orders.filter(o=>o.confirmedAt&&dateOf(o.confirmedAt)<=to&&orderBalance(state,o,to)!==0).length?orders.filter(o=>o.confirmedAt&&dateOf(o.confirmedAt)<=to&&orderBalance(state,o,to)!==0).map(o=>{const balance=orderBalance(state,o,to);return <div className="list-row" key={o.id}><div className="list-main"><Link className="text-link" to={`/pedidos/${o.id}`}>{o.code} · {o.contactName||'Venta presencial'}</Link><p>{o.status} · {o.dueDate?`Pago: ${dateLabel(o.dueDate)}`:'Fecha de cobro por acordar'}</p><Badge tone={balance<0?'warning':'neutral'}>{balance<0?'Saldo a favor':'Por cobrar'}: {money(Math.abs(balance))}</Badge></div><Button variant="secondary" onClick={()=>setOperation({kind:balance<0?'Devolución al cliente':'Cobro',orderId:o.id})}>{balance<0?'Devolver':'Cobrar'}</Button></div>}):<Empty text="No hay saldos pendientes en los compromisos registrados al corte."/>}
    </Card><Card title="Proveedores: por pagar o recuperar" subtitle="Las compras y los pagos se registran por separado">{purchases.filter(p=>p.date<=to&&purchaseBalance(state,p,to)!==0).length?purchases.filter(p=>p.date<=to&&purchaseBalance(state,p,to)!==0).map(p=>{const balance=purchaseBalance(state,p,to);return <div className="list-row" key={p.id}><div className="list-main"><strong>{p.description}</strong><p>{state.suppliers.find(s=>s.id===p.supplierId)?.name||'Proveedor por identificar'} · {p.dueDate?dateLabel(p.dueDate):'Vencimiento por acordar'}</p><Badge tone={balance<0?'warning':'neutral'}>{balance<0?'A recuperar':'Por pagar'}: {money(Math.abs(balance))}</Badge></div><Button variant="secondary" onClick={()=>setOperation({kind:balance<0?'Devolución de proveedor':'Pago',purchaseId:p.id})}>{balance<0?'Registrar devolución':'Pagar'}</Button></div>}):<Empty text="No hay obligaciones pendientes en las compras registradas al corte."/>}</Card></div>}
  {tab==='compras'&&<><Card title="Compras y gastos" action={<Button variant="secondary" onClick={()=>{setNeedId('');setEventId('');setPurchase('new');}}>Añadir compra</Button>}>{purchases.length?<div className="table-wrap"><table className="table"><thead><tr><th>Concepto / fecha</th><th>Proveedor</th><th>Importe negocio</th><th>Por pagar</th><th>Acciones</th></tr></thead><tbody>{purchases.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(p=><tr key={p.id}><td><strong>{p.description}</strong><br/>{dateLabel(p.date)} · {p.category}{p.status==='Cancelada'&&<Badge tone="danger">Cancelada</Badge>}</td><td>{state.suppliers.find(s=>s.id===p.supplierId)?.name||'Por identificar'}</td><td>{money(p.businessAmount+p.adjustments.reduce((sum,a)=>sum+a.amount,0))}{p.adjustments.length>0&&<small>Original del negocio: {money(p.businessAmount)}</small>}{p.amount!==p.businessAmount&&<small>Compra total: {money(p.amount)}</small>}</td><td>{money(purchaseBalance(state,p))}</td><td><div className="inline-actions"><Button variant="secondary" disabled={purchaseBalance(state,p)===0} onClick={()=>setOperation({kind:purchaseBalance(state,p)<0?'Devolución de proveedor':'Pago',purchaseId:p.id})}>{purchaseBalance(state,p)<0?'Devolución':'Pago'}</Button><Button variant="ghost" onClick={()=>setPurchase(p)}>Detalles</Button><Button variant="ghost" onClick={()=>setPurchaseFiles(p.id)}>Archivos</Button><Button variant="ghost" onClick={()=>setAdjust(p)}>Ajustar</Button></div></td></tr>)}</tbody></table></div>:<Empty text="Registra compras e importes comprometidos; un pago se agrega cuando salga el dinero."/>}</Card>
  <Card title="Proveedores" action={<Button variant="secondary" onClick={()=>setSupplier('new')}>Añadir proveedor</Button>}>{state.suppliers.filter(s=>!s.archived).map(s=><div key={s.id} className="list-row"><div className="list-main"><strong>{s.name}</strong><p>{s.supplies||'Suministros por documentar'} · {s.contact||'Contacto por registrar'}</p><small>{s.conditions}</small></div><Button variant="secondary" onClick={()=>setSupplier(s)}>Editar</Button></div>)}{!state.suppliers.filter(s=>!s.archived).length&&<Empty text="Conserva sólo datos y condiciones realmente comunicadas."/>}</Card></>}
  {tab==='cuentas'&&<><Card title="Cuentas y cajas" action={<Button variant="secondary" onClick={()=>setAccount('new')}>Añadir cuenta</Button>}>{state.accounts.filter(a=>!a.archived).map(a=><div className="list-row" key={a.id}><div className="list-main"><strong>{a.name}</strong><p>{a.opening===null?'Saldo inicial por registrar':`Inicio ${dateLabel(a.openingDate)}: ${money(a.opening)}`}</p><strong>{a.opening===null?'Saldo total desconocido':money(accountBalance(state,a,to))}</strong><small>{a.source}</small></div><Button variant="secondary" onClick={()=>setAccount(a)}>Editar cuenta</Button></div>)}{!state.accounts.length&&<Empty text="Añade las cuentas que utilizan realmente. No se inventa un saldo inicial."/>}</Card>
  <Card title="Comparar saldo real y registrado" action={<Button variant="secondary" onClick={()=>setReconcile(true)}>Nueva comparación</Button>}>{state.reconciliations.length?state.reconciliations.slice().reverse().map(r=><div className="list-row" key={r.id}><div className="list-main"><strong>{state.accounts.find(a=>a.id===r.accountId)?.name} · {dateLabel(r.date)}</strong><p>Contado: {money(r.counted)} · Registrado: {money(r.calculated)} · Diferencia: {r.calculated===null?'Por registrar':money(r.counted-r.calculated)}</p><small>{r.notes}</small></div></div>):<Empty text="Una diferencia se investiga. Esta comparación no crea ventas ni ajusta dinero automáticamente."/>}</Card>
  <Card title="Movimientos sin cuenta identificada"><OperationTools records={state.money.filter(m=>!m.accountId&&!m.reversedBy&&!m.reversalOf)}/></Card></>}
  <Modal open={!!operation} onClose={closeAction} title={operation?.kind||'Registrar dinero'} wide>{operation&&<MoneyForm key={`${operation.kind}-${operation.orderId}-${operation.purchaseId}`} {...operation} onClose={closeAction} onSaved={closeAction}/>}</Modal>
  <Modal open={!!purchase} onClose={closeAction} title={purchase==='new'?'Registrar compra o gasto':'Revisar compra'} wide>{purchase&&<PurchaseForm key={purchase==='new'?`new-${needId}-${eventId}`:purchase.id} initial={purchase==='new'?undefined:purchase} eventId={eventId} needId={needId} onClose={closeAction} onSaved={(purchaseId,pay)=>{closeAction();if(pay)setOperation({kind:'Pago',purchaseId});}}/>}</Modal>
  <Modal open={!!supplier} onClose={()=>setSupplier(null)} title={supplier==='new'?'Nuevo proveedor':'Editar proveedor'}>{supplier&&<SupplierForm initial={supplier==='new'?undefined:supplier} onClose={()=>setSupplier(null)}/>}</Modal>
  <Modal open={!!account} onClose={()=>setAccount(null)} title={account==='new'?'Nueva cuenta':'Revisar cuenta'}>{account&&<AccountForm initial={account==='new'?undefined:account} onClose={()=>setAccount(null)}/>}</Modal>
  <Modal open={reconcile} onClose={()=>setReconcile(false)} title="Comparar saldos"><ReconciliationForm onClose={()=>setReconcile(false)}/></Modal>
  <Modal open={!!purchaseFiles} onClose={()=>setPurchaseFiles(null)} title="Comprobantes de compra">{purchaseFiles&&<AttachmentsPanel entityType="purchases" entityId={purchaseFiles}/>}</Modal>
  <Modal open={!!adjust} onClose={()=>setAdjust(null)} title="Ajustar compra">{adjust&&<PurchaseAdjustment purchase={adjust} onClose={()=>setAdjust(null)}/>}</Modal>
  <div className="inline-actions"><Button variant="ghost" onClick={()=>exportAction(()=>exportCsv(state,'money'))}>Descargar movimientos CSV</Button><Button variant="ghost" onClick={()=>exportAction(()=>exportSummaryPdf(state,from,to))}>Resumen PDF</Button></div></div>;
}

export function MovementsScreen(){const {state}=useCRM();const [params]=useSearchParams();const [from,setFrom]=useState(params.get('from')||monthStart());const [to,setTo]=useState(params.get('to')||today());const [direction,setDirection]=useState(params.get('direction')||'Todas');const [operational,setOperational]=useState(params.get('operational')==='true');const [kind,setKind]=useState('Todas');const [account,setAccount]=useState('Todas');const [query,setQuery]=useState('');const records=useMemo(()=>state.money.filter(r=>inPeriod(r.date,from,to)&&(direction==='Todas'||r.direction===direction)&&(!operational||['Cobro','Pago','Devolución al cliente','Devolución de proveedor'].includes(r.kind))&&(kind==='Todas'||r.kind===kind)&&(account==='Todas'||(account==='pending'?!r.accountId:r.accountId===account||r.toAccountId===account))&&normalize(`${r.reference} ${r.notes} ${paymentLabel(r,state)}`).includes(normalize(query))).sort((a,b)=>b.date.localeCompare(a.date)),[state,from,to,kind,account,query,direction,operational]);return <div className="stack"><PageHeader title="Movimientos de dinero" description="Las correcciones conservan el original y su motivo. Una transferencia no es una venta." actions={<Link className="btn btn-secondary" to="/dinero">Volver a Dinero</Link>}/><div className="toolbar"><Field label="Desde"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Hasta"><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="Operación"><Select value={kind} onChange={e=>setKind(e.target.value)}><option>Todas</option>{kinds.map(k=><option key={k}>{k}</option>)}</Select></Field><Field label="Cuenta"><Select value={account} onChange={e=>setAccount(e.target.value)}><option>Todas</option><option value="pending">Por identificar</option>{state.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></Field><Field label="Dirección del movimiento"><Select value={direction} onChange={e=>setDirection(e.target.value)}><option>Todas</option><option>Entrada</option><option>Salida</option></Select></Field><label className="row"><input type="checkbox" checked={operational} onChange={e=>setOperational(e.target.checked)}/>Sólo operaciones con clientes y proveedores</label></div><Field label="Buscar referencia o pedido"><Input value={query} onChange={e=>setQuery(e.target.value)}/></Field><Card title={`${records.length} movimientos registrados`}><OperationTools records={records}/></Card></div>;}

export function ClosingScreen(){const {state,save,notify,busy}=useCRM();const [from,setFrom]=useState(monthStart());const [to,setTo]=useState(today());const [notes,setNotes,clearDraft]=useDraftState('closing:new','notes','');const [error,setError]=useState('');const summary=financialSummary(state,from,to);const pending=state.money.filter(m=>!m.accountId&&!m.reversedBy&&!m.reversalOf);async function execute(task:()=>unknown){try{if(!from||!to||from>to)throw new Error('Revisa las fechas del periodo.');await task();notify('Archivo preparado para descargar.');}catch(e){setError(fail(e));}}return <div className="stack"><PageHeader title="Revisar y exportar" description="Un reporte conserva el periodo, el corte y la versión del registro. Los archivos de recuperación son distintos de un resumen." actions={<Link className="btn btn-secondary" to="/dinero">Volver a Dinero</Link>}/><div className="toolbar"><Field label="Desde"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Hasta / corte"><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field></div><ErrorBox error={error}/>
  <Card title="Revisión del periodo"><div className="form-grid"><div><strong>Ventas y ajustes</strong><p>{money(summary.sales)}</p></div><div><strong>Cobros / devoluciones</strong><p>{money(summary.receipts)} / {money(summary.refunds)}</p></div><div><strong>Pagos / devoluciones de proveedor</strong><p>{money(summary.payments)} / {money(summary.providerRefunds)}</p></div><div><strong>Compromisos al corte</strong><p>Por cobrar {money(summary.receivable)} · Por pagar {money(summary.payable)}</p></div></div><Notice tone={pending.length?'warning':'info'}>{pending.length} movimientos activos con cuenta por identificar. {state.accounts.filter(a=>a.opening===null).length} cuentas con saldo inicial desconocido. Los registros no equivalen a libros tributarios oficiales.</Notice><Link className="text-link" to="/dinero/movimientos">Revisar movimientos</Link></Card>
  <Card title="Movimientos no operativos" subtitle="Aportes, retiros, préstamos, transferencias y ajustes de saldo"><OperationTools records={state.money.filter(m=>inPeriod(m.date,from,to)&&!['Cobro','Pago','Devolución al cliente','Devolución de proveedor'].includes(m.kind))}/></Card>
  <Card title="Guardar una revisión"><Form onSubmit={async()=>{try{if(from>to)throw new Error('Revisa el periodo.');await save('closings',{...base(),from,to,cutoff:to,notes,summary:{...summary},snapshotVersion:state.revision},notes||'Revisión del periodo');setNotes('');clearDraft();notify('Revisión conservada con su versión de datos.');}catch(e){setError(fail(e));}}}><Field label="Observaciones, límites y pendientes"><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field><Actions><Button disabled={busy}>Conservar revisión</Button></Actions></Form></Card>
  <Card title="Descargar información"><div className="inline-actions"><Button variant="secondary" onClick={()=>execute(()=>exportSummaryPdf(state,from,to))}>Resumen PDF</Button><Button variant="secondary" onClick={()=>execute(()=>exportBundle(state))}>Tablas y registros relacionados</Button><Button variant="secondary" onClick={()=>execute(()=>downloadBackup(state))}>Respaldo completo de datos</Button></div><p className="muted">El respaldo de datos no descarga automáticamente documentos adjuntos ni el PDF comercial de 324 MiB. Conserva también sus archivos originales y comprueba recuperación.</p><div className="inline-actions">{(['sales','money','purchases','clients','accounts','suppliers','reconciliations'] as const).map(c=><Button key={c} variant="ghost" onClick={()=>execute(()=>exportCsv(state,c))}>{({sales:'Ventas',money:'Dinero',purchases:'Compras',clients:'Clientes',accounts:'Cuentas',suppliers:'Proveedores',reconciliations:'Conciliaciones'} as const)[c]} · CSV</Button>)}</div></Card>
  <Card title="Revisiones conservadas">{state.closings.length?state.closings.slice().reverse().map(c=><div className="list-row" key={c.id}><div className="list-main"><strong>{dateLabel(c.from)} – {dateLabel(c.to)}</strong><p>Versión {c.snapshotVersion} · Corte {dateLabel(c.cutoff)} · Ventas {money(Number(c.summary.sales)||0)}</p><small>{c.notes||'Sin observaciones adicionales'}</small></div></div>):<Empty text="Las correcciones posteriores quedan en la historia; no borran una revisión anterior."/>}</Card></div>;}
