import {createContext,useContext,useId} from 'react';
import type {ReactNode,FormEvent,InputHTMLAttributes,SelectHTMLAttributes,TextareaHTMLAttributes,ButtonHTMLAttributes} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {X,Inbox,Plus,ArrowUpRight} from 'lucide-react';
import {Link} from 'react-router-dom';
export function Button({variant='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'}){return <button {...props} className={`btn btn-${variant} ${className}`}/>;}
const FieldContext=createContext<{labelId:string;descriptionId?:string}>({labelId:''});
export function Field({label,hint,error,children}: {label:string;hint?:string;error?:string;children:ReactNode}){const id=useId();return <FieldContext.Provider value={{labelId:id,descriptionId:hint||error?id+'-description':undefined}}><div className="field"><span id={id} className="field-label">{label}</span>{children}{(hint||error)&&<div id={id+'-description'}>{hint&&<small>{hint}</small>}{error&&<span className="field-error">{error}</span>}</div>}</div></FieldContext.Provider>;}
function fieldProps(props:{'aria-label'?:string;'aria-labelledby'?:string;'aria-describedby'?:string}){const context=useContext(FieldContext);return {'aria-labelledby':props['aria-label']?undefined:props['aria-labelledby']||context.labelId||undefined,'aria-describedby':props['aria-describedby']||context.descriptionId};}
export function Input(props:InputHTMLAttributes<HTMLInputElement>){const accessible=fieldProps(props);return <input {...accessible} {...props} className={`input ${props.className||''}`}/>;}
export function Select(props:SelectHTMLAttributes<HTMLSelectElement>){const accessible=fieldProps(props);return <select {...accessible} {...props} className={`input ${props.className||''}`}/>;}
export function Textarea(props:TextareaHTMLAttributes<HTMLTextAreaElement>){const accessible=fieldProps(props);return <textarea rows={3} {...accessible} {...props} className={`input ${props.className||''}`}/>;}
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode;wide?:boolean}){return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={`modal ${wide?'modal-wide':''}`}><header className="modal-header"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description className={description?'':'sr-only'}>{description||'Completa los datos y guarda los cambios.'}</Dialog.Description></div><Dialog.Close asChild><button className="icon-btn" aria-label="Cerrar"><X size={22}/></button></Dialog.Close></header><div className="modal-body">{children}</div></Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function PageHeader({eyebrow,title,description,actions}: {eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="page-header"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="page-actions">{actions}</div></header>;}
export function Card({title,subtitle,action,children,className=''}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`card ${className}`}>{(title||action)&&<header className="card-header"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</header>}<div className="card-body">{children}</div></section>;}
export function Empty({title='Todavía no hay registros',text,action}:{title?:string;text?:string;action?:ReactNode}){return <div className="empty"><Inbox size={30} strokeWidth={1.4}/><h3>{title}</h3>{text&&<p>{text}</p>}{action}</div>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'purple'}){return <span className={`badge badge-${tone}`}>{children}</span>;}
export function Tabs({values,value,onChange}: {values:{id:string;label:string;count?:number}[];value:string;onChange:(id:string)=>void}){return <div className="tabs" role="tablist">{values.map(v=><button key={v.id} role="tab" aria-selected={v.id===value} className={v.id===value?'active':''} onClick={()=>onChange(v.id)}>{v.label}{v.count!=null&&<span>{v.count}</span>}</button>)}</div>;}
export function Form({onSubmit,children}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void|Promise<void>;children:ReactNode}){return <form onSubmit={e=>{e.preventDefault();void onSubmit(e);}}>{children}</form>;}
export function Stat({label,value,detail,icon,tone,action}:{label:string;value:ReactNode;detail?:ReactNode;icon?:ReactNode;tone?:string;action?:ReactNode}){return <div className={`stat ${tone||''}`}><div className="stat-top"><span>{label}</span>{icon}</div><strong>{value}</strong>{detail&&<small>{detail}</small>}{action}</div>;}
export function ErrorBox({error}:{error:string}){return error?<div className="alert alert-danger" role="alert">{error}</div>:null;}
export function Notice({children,tone='info'}:{children:ReactNode;tone?:'info'|'warning'|'success'}){return <div className={`alert alert-${tone}`}>{children}</div>;}
export function Actions({children}:{children:ReactNode}){return <div className="form-actions">{children}</div>;}
export function CreateButton({children,onClick}:{children:ReactNode;onClick:()=>void}){return <Button onClick={onClick}><Plus size={18}/>{children}</Button>;}
export function InlineLink({to,children}:{to:string;children:ReactNode}){return <Link className="text-link" to={to}>{children}</Link>;}
export function ExternalLink({href,children}:{href:string;children:ReactNode}){return <a className="text-link" href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={15}/></a>;}
export function BarChart({rows,format=(n:number)=>String(n),label}:{rows:{label:string;value:number;onClick?:()=>void}[];format?:(n:number)=>string;label:string}){const max=Math.max(1,...rows.map(x=>Math.abs(x.value)));return <div className="bar-chart" aria-label={label}>{rows.length?rows.map((r,i)=><button key={r.label} onClick={r.onClick} disabled={!r.onClick} className="bar-row"><span>{r.label}</span><span className="bar-track"><span className={`bar-fill bar-${i%3} ${r.value<0?'bar-negative':''}`} style={{width:`${Math.abs(r.value)/max*100}%`}}/></span><strong>{format(r.value)}</strong></button>):<Empty text="Los gráficos aparecerán cuando registres operaciones."/>}</div>;}
